"""AWS certification manifest (message 5 of N).

Generic discovery is fully sufficient for AWS — no adapter needed.
AWS's 87 wired record types and 9 Findings span IAM/S3/networking/compute/security-hub/backup surfaces — only configuration and posture metadata is collected, never resource contents.
"""

from __future__ import annotations

from app.provider_certification.models import (
    CapabilityEvidenceDeclaration,
    FindingChangeParityEvidence,
    FindingReachabilityEvidence,
    ProviderCertificationManifest,
)
from app.provider_certification.runner import register_manifest

_EXPECTED_RECORD_TYPES = (
    "aws_account_identity",
    "aws_apigateway_rest_api",
    "aws_apigateway_rest_stage",
    "aws_apigatewayv2_api",
    "aws_apigatewayv2_stage",
    "aws_backup_plan",
    "aws_backup_recovery_point",
    "aws_backup_selection",
    "aws_backup_vault",
    "aws_cloudfront_distribution",
    "aws_cloudtrail_event_data_store",
    "aws_cloudtrail_trail",
    "aws_cloudwatch_anomaly_detector",
    "aws_cloudwatch_composite_alarm",
    "aws_cloudwatch_dashboard",
    "aws_cloudwatch_log_group",
    "aws_cloudwatch_metric_alarm",
    "aws_cloudwatch_metric_filter",
    "aws_cloudwatch_metric_stream",
    "aws_cloudwatch_subscription_filter",
    "aws_ecr_registry_scanning_config",
    "aws_ecr_repository",
    "aws_ecs_cluster",
    "aws_ecs_service",
    "aws_ecs_task_definition",
    "aws_eks_addon",
    "aws_eks_cluster",
    "aws_eks_fargate_profile",
    "aws_eks_node_group",
    "aws_elb_classic_load_balancer",
    "aws_elbv2_listener",
    "aws_elbv2_listener_rule",
    "aws_elbv2_load_balancer",
    "aws_elbv2_target_group",
    "aws_eventbridge_archive",
    "aws_eventbridge_event_bus",
    "aws_eventbridge_rule",
    "aws_eventbridge_target",
    "aws_guardduty_detector",
    "aws_guardduty_publishing_destination",
    "aws_iam_access_key",
    "aws_iam_account_summary",
    "aws_iam_group",
    "aws_iam_identity_provider",
    "aws_iam_inline_policy",
    "aws_iam_policy",
    "aws_iam_policy_attachment",
    "aws_iam_role",
    "aws_iam_user",
    "aws_internet_gateway",
    "aws_kms_alias",
    "aws_kms_key",
    "aws_lambda_alias",
    "aws_lambda_event_source_mapping",
    "aws_lambda_function",
    "aws_lambda_function_url",
    "aws_network_acl",
    "aws_organizations_account",
    "aws_organizations_organization",
    "aws_organizations_ou",
    "aws_organizations_scp",
    "aws_organizations_scp_attachment",
    "aws_rds_db_cluster",
    "aws_rds_db_cluster_snapshot",
    "aws_rds_db_instance",
    "aws_rds_db_snapshot",
    "aws_rds_db_subnet_group",
    "aws_region",
    "aws_route53_hosted_zone",
    "aws_route53_record",
    "aws_route_table",
    "aws_s3_bucket",
    "aws_secretsmanager_secret",
    "aws_security_group",
    "aws_security_group_rule",
    "aws_securityhub_account",
    "aws_securityhub_finding_aggregator",
    "aws_securityhub_standard_subscription",
    "aws_service_inventory",
    "aws_sns_subscription",
    "aws_sns_topic",
    "aws_sqs_queue",
    "aws_ssm_parameter",
    "aws_subnet",
    "aws_vpc",
    "aws_wafv2_web_acl",
    "aws_wafv2_web_acl_association",
)

_FINDING_RULE_IDS = (
    "aws_access_key_unused",
    "aws_iam_admin_policy_attached",
    "aws_iam_broad_policy_attached",
    "aws_public_admin_port",
    "aws_public_all_ports",
    "aws_public_database_port",
    "aws_root_mfa_disabled",
    "aws_s3_public_acl",
    "aws_s3_public_policy",
)

AWS_MANIFEST = ProviderCertificationManifest(
    provider_id="aws",
    display_name="AWS",
    category="cloud",
    maturity="complete",
    expected_public=True,
    expected_connectable=True,
    expected_live=True,
    credential_fields=("aws_access_key_id", "aws_secret_access_key", "aws_default_region", "aws_selected_regions"),
    sensitive_credential_fields=("aws_access_key_id", "aws_secret_access_key"),
    authentication_model="access_key",
    expected_record_types=_EXPECTED_RECORD_TYPES,
    security_finding_rule_ids=_FINDING_RULE_IDS,
    supported_capabilities=(
        "security_findings",
        "activity_ingestion",
        "activity_signals",
        "risk_activity_correlations",
        "demo_case_reporting",
    ),
    unsupported_capabilities=(),
    completeness_scopes=(),
    false_removal_scopes=(),
    expected_frontend_form="AWSIntegrationForm.tsx",
    expected_reconnect=True,
    prohibited_dependencies=(),
    known_limitations=(
        "No CloudTrail EVENT ingestion — only trail/event-data-store CONFIGURATION metadata is collected, never individual log events.",
        "No resource contents, secrets, object bodies, database rows, or log events are ingested — only configuration/posture metadata across IAM, networking, storage, compute, and security services.",
        "8 schema-declared record-type constants (aws_access_analyzer, aws_access_analyzer_finding, aws_acm_certificate, aws_config_delivery_channel, aws_config_recorder, aws_ec2_instance, aws_securityhub_finding, aws_vpc_flow_log) are dispatched by the classifier module but never actually wired into the connector — confirmed by grep, genuinely unimplemented on the connector side.",
        "No false-removal suppression function exists for AWS yet (diff_service has no _aws_removal_suppressed) — completeness_scopes/false_removal_scopes are honestly declared empty rather than claiming protection that doesn't exist.",
    ),
    evidence_test_files=(
        "tests/test_aws_provider_depth_qa.py",
        "tests/test_aws_change_classification_qa.py",
    ),
    reachability_evidence=(
        FindingReachabilityEvidence(
            provider_id="aws",
            test_file="tests/test_aws_provider_depth_qa.py",
            test_selector="",
            covered_rule_ids=_FINDING_RULE_IDS,
            minimum_test_count=25,
            quality="direct",
        ),
    ),
    change_parity_evidence=(
        FindingChangeParityEvidence(
            provider_id="aws",
            test_file="tests/test_aws_change_classification_qa.py",
            test_selector="",
            covered_rule_ids=_FINDING_RULE_IDS,
            minimum_test_count=12,
            quality="direct",
        ),
    ),
    capability_evidence=(
        CapabilityEvidenceDeclaration(
            capability="security_findings",
            supporting_record_types=(
                "aws_iam_policy", "aws_iam_role", "aws_iam_user", "aws_s3_bucket",
                "aws_security_group", "aws_security_group_rule",
            ),
            supporting_finding_rule_ids=_FINDING_RULE_IDS,
            evidence_tests=("tests/test_aws_provider_depth_qa.py",),
            limitation_note="Configuration/posture metadata only — never resource contents.",
        ),
    ),
)

register_manifest(AWS_MANIFEST)
