"""Jira certification manifest (message 5 of N).

Generic discovery is fully sufficient for Jira — no adapter needed.
Jira is registered in PROVIDER_CAPABILITIES_PARTIAL (maturity='partial'), matching this manifest's declared maturity.
"""

from __future__ import annotations

from app.provider_certification.models import (
    FindingChangeParityEvidence,
    FindingReachabilityEvidence,
    ProviderCertificationManifest,
)
from app.provider_certification.runner import register_manifest

_EXPECTED_RECORD_TYPES = (
    "jira_automation_rule",
    "jira_board",
    "jira_field_configuration_scheme",
    "jira_issue_type_scheme",
    "jira_notification_scheme",
    "jira_permission_scheme",
    "jira_project",
    "jira_screen_scheme",
    "jira_site",
    "jira_webhook",
    "jira_workflow",
    "jira_workflow_scheme",
)

_FINDING_RULE_IDS = (
    "jira_automation_rule_comment_action",
    "jira_automation_rule_disabled",
    "jira_automation_rule_email_action",
    "jira_automation_rule_external_action",
    "jira_automation_rule_global_scope",
    "jira_automation_rule_high_action_count",
    "jira_automation_rule_high_branch_count",
    "jira_automation_rule_high_component_count",
    "jira_automation_rule_multi_project_scope",
    "jira_automation_rule_unknown_scope",
    "jira_automation_rule_unknown_trigger",
    "jira_automation_rule_web_request_action",
    "jira_board_broad_jql_filter",
    "jira_board_high_quick_filter_count",
    "jira_board_missing_project_link",
    "jira_board_no_columns",
    "jira_board_no_filter_indicator",
    "jira_board_unknown_location_type",
    "jira_board_unknown_swimlane_strategy",
    "jira_board_unknown_type_category",
    "jira_issue_type_scheme_no_default",
    "jira_notification_scheme_email_recipients",
    "jira_notification_scheme_group_recipients",
    "jira_notification_scheme_high_event_count",
    "jira_notification_scheme_no_notifications",
    "jira_notification_scheme_unknown_recipients",
    "jira_permission_scheme_anonymous_grant",
    "jira_permission_scheme_anyone_grant",
    "jira_permission_scheme_high_grant_count",
    "jira_permission_scheme_high_privilege_grants",
    "jira_permission_scheme_high_public_grant_count",
    "jira_permission_scheme_logged_in_grant",
    "jira_permission_scheme_public_administer_projects",
    "jira_permission_scheme_public_browse_projects",
    "jira_permission_scheme_public_create_issues",
    "jira_permission_scheme_public_manage_sprints",
    "jira_permission_scheme_public_transition_issues",
    "jira_permission_scheme_unknown_holder",
    "jira_project_archived",
    "jira_project_deleted",
    "jira_project_missing_key",
    "jira_project_no_lead",
    "jira_project_private",
    "jira_project_simplified",
    "jira_project_unknown_style_category",
    "jira_project_unknown_type_category",
    "jira_screen_scheme_no_screens",
    "jira_screen_scheme_unmapped_screens",
    "jira_site_missing_url",
    "jira_site_no_automation_rules",
    "jira_site_no_projects",
    "jira_site_no_webhooks",
    "jira_webhook_all_issue_events",
    "jira_webhook_attachment_event_scope",
    "jira_webhook_broad_event_scope",
    "jira_webhook_comment_event_scope",
    "jira_webhook_disabled",
    "jira_webhook_no_events",
    "jira_webhook_no_jql_filter",
    "jira_webhook_no_secret_indicator",
    "jira_webhook_non_https",
    "jira_webhook_sprint_event_scope",
    "jira_webhook_worklog_event_scope",
    "jira_workflow_draft",
    "jira_workflow_excessive_global_transitions",
    "jira_workflow_high_condition_count",
    "jira_workflow_high_post_function_count",
    "jira_workflow_high_transition_rule_count",
    "jira_workflow_high_validator_count",
    "jira_workflow_inactive",
    "jira_workflow_no_done_status",
    "jira_workflow_no_in_progress_status",
    "jira_workflow_no_statuses",
    "jira_workflow_no_transitions",
    "jira_workflow_orphan_statuses",
    "jira_workflow_scheme_high_issue_type_mapping_count",
    "jira_workflow_scheme_low_project_count",
    "jira_workflow_scheme_low_workflow_count",
    "jira_workflow_scheme_no_default",
    "jira_workflow_scheme_unmapped_issue_types",
    "jira_workflow_scheme_unused",
)

JIRA_MANIFEST = ProviderCertificationManifest(
    provider_id="jira",
    display_name="Jira",
    category="devops",
    maturity="partial",
    expected_public=True,
    expected_connectable=True,
    expected_live=False,
    credential_fields=("jira_site_url", "jira_email", "jira_api_token"),
    sensitive_credential_fields=("jira_api_token",),
    authentication_model="api_token",
    expected_record_types=_EXPECTED_RECORD_TYPES,
    security_finding_rule_ids=_FINDING_RULE_IDS,
    supported_capabilities=(
        "security_findings",
        "activity_ingestion",
        "activity_signals",
        "risk_activity_correlations",
        "demo_case_reporting",
    ),
    unsupported_capabilities=(),
    completeness_scopes=(),
    false_removal_scopes=(),
    expected_frontend_form="JiraIntegrationForm.tsx",
    expected_reconnect=False,
    prohibited_dependencies=(),
    known_limitations=(
        "No issue descriptions, comments, attachments, worklogs, user-generated issue content, or activity-history ingestion — only project/board/scheme/workflow/webhook/automation-rule CONFIGURATION metadata.",
        "No reconnect function or dispatch is wired for Jira yet.",
        "No false-removal suppression function exists for Jira yet.",
    ),
    evidence_test_files=(
        "tests/test_jira_provider_depth_qa.py",
        "tests/test_jira_provider_depth_qa.py",
    ),
    reachability_evidence=(
        FindingReachabilityEvidence(
            provider_id="jira",
            test_file="tests/test_jira_provider_depth_qa.py",
            test_selector="",
            covered_rule_ids=_FINDING_RULE_IDS,
            minimum_test_count=15,
            quality="direct",
        ),
    ),
    change_parity_evidence=(
        FindingChangeParityEvidence(
            provider_id="jira",
            test_file="tests/test_jira_provider_depth_qa.py",
            test_selector="",
            covered_rule_ids=_FINDING_RULE_IDS,
            minimum_test_count=15,
            quality="direct",
        ),
    ),
)

register_manifest(JIRA_MANIFEST)
