"""Dodo existing-subscription plan-change regression tests (fix for a
confirmed production double-billing bug).

Root cause: a workspace with an existing, active Dodo subscription that
clicked another paid plan (Pro -> Team or Team -> Pro) was routed through
the exact same ``adapter.create_checkout`` path a brand-new Free
workspace uses — creating a SECOND, independent Dodo subscription while
the original stayed active and billable. Confirmed via the real Dodo
dashboard: both a Pro subscription ($10/mo) and a new Team subscription
($30/mo) were simultaneously Active for one workspace after a Pro ->
Team "upgrade".

Fix: ``_create_plan_checkout`` (app/routers/billing.py) now checks for an
existing, live ``NormalizedSubscription`` row BEFORE ever calling
``adapter.create_checkout``. If that row belongs to Dodo and is in a live
status, the request is routed to ``_change_existing_dodo_plan``, which
calls the new ``DodoBillingAdapter.change_subscription_plan`` — built on
the already-verified ``POST /subscriptions/{id}/change-plan`` endpoint
(the same one ``update_subscription`` already used for Team seat
changes) — against the EXISTING subscription ID. No new Dodo subscription
is ever created for an existing Dodo customer.

Router-level tests here monkeypatch ``get_adapter_for_provider`` with a
recording fake adapter — no real or mocked HTTP call is made, and
therefore no live or Test Mode Dodo API traffic is generated by this
file at all. Adapter-payload-level tests (proration, product_id, addon
handling) reuse the exact ``httpx.MockTransport`` pattern already
established in ``test_commercial_dodo_checkout.py``.
"""

from __future__ import annotations

import uuid

import httpx
import pytest
from fastapi import HTTPException

from app.billing.adapters.dodo import DodoBillingAdapter, DodoCatalogMapping, DodoUnsupportedPlanError
from app.billing.dodo_client import DodoAPIClient, DodoClientConfig
from app.billing.enums import BillingProvider, PlanId
from app.billing.models import NormalizedSubscription
from app.billing.provider import BillingProviderReference, ProviderOperationResult
from app.models.workspace import Workspace, WorkspaceMember


# ── Adapter-level payload tests (mocked HTTP, no router involved) ──────────


def _mapping() -> DodoCatalogMapping:
    return DodoCatalogMapping(
        environment="test", pro_product_id="prod_pro_test",
        team_product_id="prod_team_test", team_seat_addon_id="addon_seat_test",
    )


def _adapter(handler) -> DodoBillingAdapter:
    transport = httpx.MockTransport(handler)
    client = DodoAPIClient(DodoClientConfig(environment="test", api_key="apikey_test_dummy"), transport=transport)
    return DodoBillingAdapter(_mapping(), client)


def _sub_ref(external_id: str) -> BillingProviderReference:
    return BillingProviderReference(
        provider=BillingProvider.DODO, object_type=__import__("app.billing.enums", fromlist=["ObjectType"]).ObjectType.SUBSCRIPTION,
        external_id=external_id, workspace_id=uuid.uuid4(),
    )


class TestChangeSubscriptionPlanPayload:
    def test_pro_to_team_calls_change_plan_not_checkout(self):
        calls = {"checkout": 0, "change_plan": []}

        def handler(request: httpx.Request) -> httpx.Response:
            calls["checkout"] += 1
            return httpx.Response(200, json={})

        adapter = _adapter(handler)

        def fake_change_plan(subscription_id, *, body, correlation_id=None):
            calls["change_plan"].append((subscription_id, body))
            return {"subscription_id": subscription_id}

        adapter._client.change_plan = fake_change_plan  # type: ignore[method-assign]

        result = adapter.change_subscription_plan(
            subscription_reference=_sub_ref("sub_pro_1"), target_plan_id=PlanId.TEAM, billable_seat_count=1,
        )
        assert calls["checkout"] == 0
        assert len(calls["change_plan"]) == 1
        sub_id, body = calls["change_plan"][0]
        assert sub_id == "sub_pro_1"  # SAME subscription ID — never a new one
        assert body["product_id"] == "prod_team_test"
        assert isinstance(result, ProviderOperationResult)
        assert result.state == "ok"

    def test_team_to_pro_calls_change_plan_with_pro_product(self):
        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(200, json={})

        adapter = _adapter(handler)
        captured = {}

        def fake_change_plan(subscription_id, *, body, correlation_id=None):
            captured["sub_id"] = subscription_id
            captured["body"] = body
            return {}

        adapter._client.change_plan = fake_change_plan  # type: ignore[method-assign]

        adapter.change_subscription_plan(
            subscription_reference=_sub_ref("sub_team_1"), target_plan_id=PlanId.PRO, billable_seat_count=25,
        )
        assert captured["sub_id"] == "sub_team_1"
        assert captured["body"]["product_id"] == "prod_pro_test"
        assert captured["body"]["addons"] == []  # Pro never carries the Team seat add-on

    def test_upgrade_to_team_uses_prorated_immediately(self):
        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(200, json={})

        adapter = _adapter(handler)
        captured = {}
        adapter._client.change_plan = lambda sub_id, *, body, correlation_id=None: captured.update(body=body) or {}  # type: ignore

        adapter.change_subscription_plan(
            subscription_reference=_sub_ref("sub_1"), target_plan_id=PlanId.TEAM, billable_seat_count=1,
        )
        assert captured["body"]["proration_billing_mode"] == "prorated_immediately"

    def test_downgrade_to_pro_uses_do_not_bill(self):
        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(200, json={})

        adapter = _adapter(handler)
        captured = {}
        adapter._client.change_plan = lambda sub_id, *, body, correlation_id=None: captured.update(body=body) or {}  # type: ignore

        adapter.change_subscription_plan(
            subscription_reference=_sub_ref("sub_1"), target_plan_id=PlanId.PRO, billable_seat_count=1,
        )
        assert captured["body"]["proration_billing_mode"] == "do_not_bill"

    def test_team_seat_addon_included_when_over_20_members(self):
        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(200, json={})

        adapter = _adapter(handler)
        captured = {}
        adapter._client.change_plan = lambda sub_id, *, body, correlation_id=None: captured.update(body=body) or {}  # type: ignore

        adapter.change_subscription_plan(
            subscription_reference=_sub_ref("sub_1"), target_plan_id=PlanId.TEAM, billable_seat_count=25,
        )
        assert captured["body"]["addons"] == [{"addon_id": "addon_seat_test", "quantity": 5}]

    def test_unsupported_plan_raises_not_guessed(self):
        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(200, json={})

        adapter = _adapter(handler)  # fully configured mapping — FREE simply has no product_id
        with pytest.raises(DodoUnsupportedPlanError):
            adapter.change_subscription_plan(
                subscription_reference=_sub_ref("sub_1"), target_plan_id=PlanId.FREE, billable_seat_count=1,
            )


# ── Router-level tests (fake adapter, no HTTP at all) ───────────────────────


class _FakeDodoAdapter:
    """Records calls; never performs I/O. Used to prove the router picks
    the plan-change path instead of create_checkout, without depending on
    real or mocked Dodo HTTP traffic."""

    def __init__(self):
        self.create_checkout_calls: list = []
        self.change_subscription_plan_calls: list = []

    def create_checkout(self, request):
        self.create_checkout_calls.append(request)
        from app.billing.provider import CheckoutResponse

        return CheckoutResponse(
            provider=BillingProvider.DODO, checkout_url="https://test.checkout.dodopayments.com/new",
            external_reference="cks_new",
        )

    def change_subscription_plan(self, *, subscription_reference, target_plan_id, billable_seat_count):
        self.change_subscription_plan_calls.append((subscription_reference, target_plan_id, billable_seat_count))
        return ProviderOperationResult(state="ok", detail="changed")


@pytest.fixture
def workspace(db_session, test_user):
    ws = Workspace(name=f"dodo-planchange-{uuid.uuid4().hex[:8]}", created_by_user_id=test_user.id)
    db_session.add(ws)
    db_session.flush()
    db_session.add(WorkspaceMember(workspace_id=ws.id, user_id=test_user.id, role="owner"))
    db_session.commit()
    db_session.refresh(ws)
    yield ws
    db_session.query(NormalizedSubscription).filter(NormalizedSubscription.workspace_id == ws.id).delete()
    db_session.commit()


def _dodo_row(db_session, workspace, *, plan_id="pro", status="active", subscription_id="sub_pro_1"):
    sub = NormalizedSubscription(
        workspace_id=workspace.id, provider="dodo", plan_id=plan_id, status=status,
        provider_customer_reference="cus_1", provider_subscription_reference=subscription_id,
        billable_seats=0, additional_seat_quantity=0,
    )
    db_session.add(sub)
    db_session.commit()
    db_session.refresh(sub)
    return sub


def _call_create_plan_checkout(monkeypatch, plan_id, workspace, db_session, test_user, fake_adapter=None):
    from app.routers import billing as billing_router

    adapter = fake_adapter if fake_adapter is not None else _FakeDodoAdapter()
    monkeypatch.setattr(billing_router, "get_adapter_for_provider", lambda provider, db: adapter)
    monkeypatch.setattr(billing_router, "provider_for_checkout", lambda workspace_id, db: BillingProvider.DODO)
    monkeypatch.setattr(billing_router, "dodo_pilot_override_active", lambda workspace_id: False)
    result = billing_router._create_plan_checkout(plan_id, workspace.id, db_session, test_user)
    return result, adapter


class TestFreeWorkspaceStillCreatesCheckout:
    def test_free_to_pro_creates_checkout(self, monkeypatch, workspace, db_session, test_user):
        result, adapter = _call_create_plan_checkout(monkeypatch, PlanId.PRO, workspace, db_session, test_user)
        assert len(adapter.create_checkout_calls) == 1
        assert len(adapter.change_subscription_plan_calls) == 0
        assert result.requires_redirect is True
        assert result.checkout_url == "https://test.checkout.dodopayments.com/new"

    def test_free_to_team_creates_checkout(self, monkeypatch, workspace, db_session, test_user):
        result, adapter = _call_create_plan_checkout(monkeypatch, PlanId.TEAM, workspace, db_session, test_user)
        assert len(adapter.create_checkout_calls) == 1
        assert len(adapter.change_subscription_plan_calls) == 0
        assert result.requires_redirect is True


class TestExistingDodoSubscriptionUsesPlanChangePath:
    def test_pro_to_team_uses_plan_change_not_checkout(self, monkeypatch, workspace, db_session, test_user):
        _dodo_row(db_session, workspace, plan_id="pro", status="active", subscription_id="sub_pro_1")
        result, adapter = _call_create_plan_checkout(monkeypatch, PlanId.TEAM, workspace, db_session, test_user)

        assert len(adapter.create_checkout_calls) == 0  # never a second subscription
        assert len(adapter.change_subscription_plan_calls) == 1
        ref, target_plan, seats = adapter.change_subscription_plan_calls[0]
        assert ref.external_id == "sub_pro_1"
        assert target_plan == PlanId.TEAM
        assert result.requires_redirect is False
        assert result.checkout_url is None

    def test_team_to_pro_uses_plan_change_not_checkout(self, monkeypatch, workspace, db_session, test_user):
        _dodo_row(db_session, workspace, plan_id="team", status="active", subscription_id="sub_team_1")
        result, adapter = _call_create_plan_checkout(monkeypatch, PlanId.PRO, workspace, db_session, test_user)

        assert len(adapter.create_checkout_calls) == 0
        assert len(adapter.change_subscription_plan_calls) == 1
        ref, target_plan, _ = adapter.change_subscription_plan_calls[0]
        assert ref.external_id == "sub_team_1"
        assert target_plan == PlanId.PRO
        assert result.requires_redirect is False

    def test_trialing_status_also_uses_plan_change_path(self, monkeypatch, workspace, db_session, test_user):
        _dodo_row(db_session, workspace, plan_id="pro", status="trialing", subscription_id="sub_pro_trial")
        result, adapter = _call_create_plan_checkout(monkeypatch, PlanId.TEAM, workspace, db_session, test_user)
        assert len(adapter.change_subscription_plan_calls) == 1
        assert len(adapter.create_checkout_calls) == 0


class TestSamePlanRequestDoesNotDuplicate:
    def test_same_plan_raises_400_no_mutation(self, monkeypatch, workspace, db_session, test_user):
        _dodo_row(db_session, workspace, plan_id="pro", status="active", subscription_id="sub_pro_1")
        with pytest.raises(HTTPException) as exc_info:
            _call_create_plan_checkout(monkeypatch, PlanId.PRO, workspace, db_session, test_user)
        assert exc_info.value.status_code == 400


class TestCanceledOrExpiredDodoRowFallsBackToCheckout:
    def test_canceled_row_creates_new_checkout(self, monkeypatch, workspace, db_session, test_user):
        _dodo_row(db_session, workspace, plan_id="pro", status="canceled", subscription_id="sub_pro_old")
        result, adapter = _call_create_plan_checkout(monkeypatch, PlanId.TEAM, workspace, db_session, test_user)
        assert len(adapter.create_checkout_calls) == 1
        assert len(adapter.change_subscription_plan_calls) == 0

    def test_expired_row_creates_new_checkout(self, monkeypatch, workspace, db_session, test_user):
        _dodo_row(db_session, workspace, plan_id="team", status="expired", subscription_id="sub_team_old")
        result, adapter = _call_create_plan_checkout(monkeypatch, PlanId.PRO, workspace, db_session, test_user)
        assert len(adapter.create_checkout_calls) == 1
        assert len(adapter.change_subscription_plan_calls) == 0


class TestMissingSubscriptionReferenceFailsClosed:
    def test_no_subscription_reference_raises_400(self, monkeypatch, workspace, db_session, test_user):
        sub = NormalizedSubscription(
            workspace_id=workspace.id, provider="dodo", plan_id="pro", status="active",
            provider_customer_reference="cus_1", provider_subscription_reference=None,
        )
        db_session.add(sub)
        db_session.commit()
        with pytest.raises(HTTPException) as exc_info:
            _call_create_plan_checkout(monkeypatch, PlanId.TEAM, workspace, db_session, test_user)
        assert exc_info.value.status_code == 400


class TestStripeAndPaddleUnaffected:
    def test_stripe_workspace_still_uses_create_checkout(self, monkeypatch, workspace, db_session, test_user):
        sub = NormalizedSubscription(
            workspace_id=workspace.id, provider="stripe", plan_id="pro", status="active",
            provider_customer_reference="cus_stripe", provider_subscription_reference="sub_stripe_1",
        )
        db_session.add(sub)
        db_session.commit()

        from app.routers import billing as billing_router

        fake_adapter = _FakeDodoAdapter()
        monkeypatch.setattr(billing_router, "get_adapter_for_provider", lambda provider, db: fake_adapter)
        monkeypatch.setattr(billing_router, "provider_for_checkout", lambda workspace_id, db: BillingProvider.STRIPE)
        monkeypatch.setattr(billing_router, "dodo_pilot_override_active", lambda workspace_id: False)
        result = billing_router._create_plan_checkout(PlanId.TEAM, workspace.id, db_session, test_user)

        assert len(fake_adapter.create_checkout_calls) == 1
        assert len(fake_adapter.change_subscription_plan_calls) == 0
        assert result.requires_redirect is True

    def test_paddle_workspace_still_uses_create_checkout(self, monkeypatch, workspace, db_session, test_user):
        sub = NormalizedSubscription(
            workspace_id=workspace.id, provider="paddle", plan_id="pro", status="active",
            provider_customer_reference="cus_paddle", provider_subscription_reference="sub_paddle_1",
        )
        db_session.add(sub)
        db_session.commit()

        from app.routers import billing as billing_router

        fake_adapter = _FakeDodoAdapter()
        monkeypatch.setattr(billing_router, "get_adapter_for_provider", lambda provider, db: fake_adapter)
        monkeypatch.setattr(billing_router, "provider_for_checkout", lambda workspace_id, db: BillingProvider.PADDLE)
        monkeypatch.setattr(billing_router, "dodo_pilot_override_active", lambda workspace_id: False)
        result = billing_router._create_plan_checkout(PlanId.TEAM, workspace.id, db_session, test_user)

        assert len(fake_adapter.create_checkout_calls) == 1
        assert len(fake_adapter.change_subscription_plan_calls) == 0


class TestNoNormalizedSubscriptionRowUnaffected:
    def test_no_row_at_all_creates_checkout(self, monkeypatch, workspace, db_session, test_user):
        result, adapter = _call_create_plan_checkout(monkeypatch, PlanId.PRO, workspace, db_session, test_user)
        assert len(adapter.create_checkout_calls) == 1
        assert len(adapter.change_subscription_plan_calls) == 0


class TestAuditEventRecordedForPlanChange:
    def test_plan_change_records_subscription_changed_audit_event(self, monkeypatch, workspace, db_session, test_user):
        from app.billing.models import BillingAuditEvent

        _dodo_row(db_session, workspace, plan_id="pro", status="active", subscription_id="sub_pro_1")
        _call_create_plan_checkout(monkeypatch, PlanId.TEAM, workspace, db_session, test_user)

        events = (
            db_session.query(BillingAuditEvent)
            .filter(BillingAuditEvent.workspace_id == workspace.id)
            .all()
        )
        assert any(e.event_type == "subscription_changed" for e in events)
        db_session.query(BillingAuditEvent).filter(BillingAuditEvent.workspace_id == workspace.id).delete()
        db_session.commit()


class TestDbRowNotMutatedDirectlyByRouter:
    """The webhook remains the single source of truth for plan_id/status —
    the router only ever calls the Dodo-side API; it never mutates the
    NormalizedSubscription row itself (that would be a second, unverified
    source of truth for entitlements)."""

    def test_row_plan_id_unchanged_until_webhook_arrives(self, monkeypatch, workspace, db_session, test_user):
        sub = _dodo_row(db_session, workspace, plan_id="pro", status="active", subscription_id="sub_pro_1")
        _call_create_plan_checkout(monkeypatch, PlanId.TEAM, workspace, db_session, test_user)
        db_session.refresh(sub)
        assert sub.plan_id == "pro"  # unchanged locally; webhook will update it
