"""Security rule confidence registry — M62.4.

Per-rule confidence metadata used to make findings more trustworthy and
explainable. Confidence describes HOW the rule reached its conclusion, not how
severe the issue is (severity stays the routing/priority signal):

  * high   — backed by a direct normalized field that clearly indicates the
             risky state.
  * medium — backed by strong provider metadata, but may depend on environment
             context.
  * low    — inferred from limited/ambiguous signals; such rules are deferred
             and do NOT emit active findings (none of the implemented rules are
             low).

The ``false_positive_guard`` text mirrors the conservative guard already shown
in the frontend Security Rules catalog, so the same explanation is consistent
across the rules catalog and individual finding detail.

This is metadata only — it never claims a confirmed exploit/breach.
"""

from __future__ import annotations

from app.services.security_rule_registry import KNOWN_RULE_KEYS, base_rule_key

HIGH = "high"
MEDIUM = "medium"
LOW = "low"

VALID_CONFIDENCE = frozenset({HIGH, MEDIUM, LOW})

_REASON = {
    HIGH: "Backed by a direct normalized field that clearly indicates the risky state.",
    MEDIUM: "Backed by strong provider metadata, but may depend on environment context.",
    LOW: "Inferred from limited or ambiguous signals; treated conservatively.",
}

# rule_key → (confidence, false_positive_guard). Confidence values mirror the
# frontend securityRuleCatalog; every implemented rule is high or medium.
RULE_CONFIDENCE: dict[str, tuple[str, str]] = {
    # GitHub
    "github_webhook_http": (HIGH, "Only fires for active webhooks whose URL begins with http://."),
    "github_branch_protection_missing": (HIGH, "Only the default branch is evaluated; a permission error aborts before this fires."),
    "github_force_pushes_allowed": (HIGH, "Only evaluated when branch protection is enabled."),
    "github_branch_deletion_allowed": (HIGH, "Only evaluated when branch protection is enabled."),
    "github_pr_review_not_required": (HIGH, "Only evaluated when branch protection is enabled."),
    "github_status_checks_not_required": (HIGH, "Only evaluated when branch protection is enabled."),
    "github_deploy_key_write_access": (HIGH, "A missing read_only flag defaults to read-only (safe); partial records are ignored."),
    "github_env_protection_missing": (HIGH, "Narrowly scoped to environments explicitly named production/prod."),
    # GitHub rulesets (M69.5A)
    "github_ruleset_not_enforced": (HIGH, "Reads the ruleset's enforcement field directly; only fires when it is not 'active'."),
    "github_ruleset_force_push_allowed": (HIGH, "Only fires for active branch rulesets that lack a non-fast-forward (block force push) rule."),
    "github_ruleset_pr_review_missing": (MEDIUM, "Depends on the protected-branch target heuristic; only active branch rulesets are evaluated."),
    "github_ruleset_status_checks_missing": (MEDIUM, "Depends on the protected-branch target heuristic; only active branch rulesets are evaluated."),
    "github_ruleset_bypass_actors_present": (HIGH, "Reads the bypass-actor count directly; counts only, never identities."),
    "github_ruleset_weak_target_coverage": (MEDIUM, "Based on a default-branch coverage heuristic; conservative and may under-report."),
    # GitHub automation permissions (M69.5B)
    "github_automation_admin_permission": (HIGH, "Reads the authenticated credential's repository permission object directly."),
    "github_automation_write_permission": (HIGH, "Reads the authenticated credential's repository permission object directly."),
    "github_token_broad_scopes": (MEDIUM, "Classic-PAT scopes only (from X-OAuth-Scopes); fine-grained tokens/Apps expose no scopes, so it may under-report."),
    "github_webhook_secret_missing": (HIGH, "GitHub reliably masks a configured secret and omits the field when none is set."),
    # GitHub new QA rules
    "github_actions_broad_permissions": (HIGH, "Only fires when allowed_actions is exactly 'all' on a github_actions_permissions record."),
    "github_branch_admin_bypass_allowed": (HIGH, "Only fires when protection_enabled=True and enforce_admins is explicitly False on a github_branch_protection record."),
    # AWS
    "aws_public_admin_port": (HIGH, "Only 0.0.0.0/0 or ::/0 count as public; reachability is not claimed."),
    "aws_public_database_port": (HIGH, "Only canonical 'any' CIDRs count as public."),
    "aws_public_all_ports": (HIGH, "Only canonical 'any' CIDRs count as public."),
    "aws_s3_public_policy": (HIGH, "Only an explicit public flag fires; an unknown state is never treated as public."),
    "aws_s3_public_acl": (HIGH, "Only an explicit public grant fires; an unknown state is never treated as public."),
    "aws_iam_admin_policy_attached": (HIGH, "Exact AdministratorAccess ARN match, not a keyword guess."),
    "aws_iam_broad_policy_attached": (HIGH, "Exact match against an allowlist of broad AWS-managed policy ARNs, not a keyword guess."),
    "aws_root_mfa_disabled": (HIGH, "Only an explicit mfa_enabled_for_root=False fires; an unknown state is never treated as disabled."),
    "aws_access_key_unused": (HIGH, "An unknown last-used age (never-used vs fetch-failed) is not flagged."),
    # Cloudflare
    "cloudflare_ssl_mode_weak": (HIGH, "Only off/flexible fire; full/strict are treated as safe."),
    "cloudflare_always_https_off": (HIGH, "Only fires when the value is explicitly 'off'."),
    "cloudflare_min_tls_weak": (HIGH, "Only TLS 1.0/1.1 fire."),
    "cloudflare_security_level_low": (HIGH, "Only off/essentially_off fire; low/medium/high are treated as normal."),
    "cloudflare_development_mode_on": (HIGH, "Only fires when development mode is explicitly 'on'."),
    "cloudflare_hsts_disabled": (HIGH, "Only an explicit enabled=false fires; indeterminate values are skipped."),
    "cloudflare_waf_rule_disabled": (HIGH, "Disabled log/skip rules are ignored — only protective actions fire."),
    "cloudflare_dns_private_origin": (HIGH, "Public/global IPs are normal and never flagged; non-IP content is ignored."),
    "cloudflare_access_policy_bypass": (HIGH, "Only fires when decision is exactly 'bypass'; allow/deny/non-bypass decisions are never flagged."),
    "cloudflare_access_policy_disabled": (HIGH, "Only fires when enabled is explicitly False; absent or unknown values are never flagged."),
    # Supabase
    "supabase_rls_disabled": (HIGH, "Only an explicit rls_enabled=false fires; missing/unknown is skipped."),
    "supabase_anonymous_access_enabled": (MEDIUM, "Anonymous auth is a feature; risky mainly with weak RLS, so wording stays careful."),
    "supabase_jwt_expiry_long": (HIGH, "Only a concrete value over the threshold fires; unknown values are skipped."),
    "supabase_public_select_sensitive_table": (HIGH, "Only fires when a public/anon SELECT policy is active on an RLS-enabled, sensitively-named table."),
    "supabase_public_write_policy": (HIGH, "Only fires when a public/anon insert/update/delete policy is active on an RLS-enabled table."),
    "supabase_edge_function_jwt_disabled": (HIGH, "Only an explicit verify_jwt=false fires; missing/unknown is skipped."),
    "supabase_auth_protection_missing": (MEDIUM, "Only an explicit leaked-password-protection=false fires; missing/unknown is skipped."),
    # Firebase
    "firebase_rules_public": (MEDIUM, "Low-confidence ruleset parses are skipped to avoid false positives."),
    "firebase_storage_rules_public": (MEDIUM, "Low-confidence ruleset parses are skipped to avoid false positives."),
    "firebase_anonymous_auth_enabled": (MEDIUM, "Risky mainly when paired with permissive rules; reported at medium severity."),
    # Firebase — M72A
    "firebase_database_public_read": (HIGH, "Only an explicit unconditional '.read': true (no auth guard) fires; low-confidence parses are skipped."),
    "firebase_database_public_write": (HIGH, "Only an explicit unconditional '.write': true (no auth guard) fires; low-confidence parses are skipped."),
    "firebase_auth_protection_missing": (MEDIUM, "Only an explicit mfa_enabled=false fires; missing/unknown is skipped."),
    # Stripe
    "stripe_webhook_http": (HIGH, "Only an explicit http scheme fires; disabled endpoints are not flagged."),
    # Stripe — M73A
    "stripe_webhook_disabled": (HIGH, "Only an explicit status='disabled' fires; enabled/unknown is skipped."),
    "stripe_webhook_broad_events": (MEDIUM, "Fires on the wildcard '*' or a large explicit event count; a normal scoped list is not flagged."),
    "stripe_payment_link_tax_disabled": (HIGH, "Only an active link with an explicit automatic_tax_enabled=false fires."),
    "stripe_payment_link_promo_codes_enabled": (HIGH, "Only an active link with an explicit allow_promotion_codes=true fires; a config-review item, not an exposure."),
    "stripe_portal_subscription_cancel_enabled": (HIGH, "Only an active portal config with an explicit subscription_cancel_enabled=true fires."),
    "stripe_portal_login_enabled": (HIGH, "Only an active portal config with an explicit login_page_enabled=true fires."),
    "stripe_account_capability_incomplete": (HIGH, "Only an explicit charges/payouts/details flag of false fires; missing/unknown is skipped."),
    # Vercel
    "vercel_preview_unprotected": (MEDIUM, "Only fires when every protection mechanism is off; previews are not production data."),
    "vercel_production_branch_missing": (MEDIUM, "Only fires when a git repository is connected but no production branch is configured."),
    "vercel_production_branch_unusual": (MEDIUM, "Only fires when the production branch matches a known non-production name; main/master/prod are treated as normal."),
    "vercel_domain_unverified": (MEDIUM, "Only an explicit verified=false fires; verified or unknown domains are skipped."),
    "vercel_env_var_broad_target": (MEDIUM, "Only fires when one variable spans production and a non-production environment."),
    "vercel_sensitive_env_var_broad_scope": (HIGH, "Only fires when a secret-suggestive key name is also scoped to a non-production environment; the value is never read."),
    "vercel_deploy_hook_production_branch": (MEDIUM, "Only fires when a deploy hook's target ref is the production branch; the hook URL is never stored."),
    # Shopify
    "shopify_webhook_http": (HIGH, "Only an explicit http scheme fires; non-HTTP transports are ignored."),
    # Shopify — M74A
    "shopify_webhook_high_risk_topic": (MEDIUM, "Only a curated set of high-risk topic prefixes / handles fires; generic topics are not flagged."),
    "shopify_app_broad_write_scopes": (HIGH, "Only the curated high-risk write scopes are counted (not generic write_* scopes); fires at >= 3."),
    "shopify_app_customer_data_scope": (HIGH, "Only an exact read_customers / write_customers grant fires; broader 'customer'-substring scopes are not used."),
    "shopify_domain_ssl_missing": (HIGH, "Only an explicit ssl_enabled=false on the primary domain fires."),
    "shopify_domain_unverified": (HIGH, "Only an explicit verified=false on the primary domain fires."),
    "shopify_policy_missing": (HIGH, "Only an explicit present=false on a canonical-policy baseline record fires."),
    # Azure — M77B
    "azure_nsg_public_admin_ingress": (HIGH, "Only Inbound+Allow rules from canonical public prefixes (*, 0.0.0.0/0, ::/0, Internet, Any) on a known admin/database/cache/search port fire."),
    "azure_nsg_public_broad_ingress": (HIGH, "Only Inbound+Allow rules from canonical public prefixes with a broad/all-port destination range fire."),
    "azure_storage_public_blob_access": (HIGH, "Only an explicit allowBlobPublicAccess=true on the storage account fires; container ACLs are not claimed."),
    "azure_storage_public_network_access": (HIGH, "Only an explicit publicNetworkAccess=Enabled fires; severity bumps to high when defaultAction=Allow is also explicit."),
    "azure_storage_weak_tls": (HIGH, "Only explicit minimumTlsVersion=TLS1_0/TLS1_1 fires; missing/unknown is skipped."),
    "azure_storage_shared_key_enabled": (HIGH, "Only an explicit allowSharedKeyAccess=true fires; missing/unknown is skipped."),
    "azure_key_vault_public_network_access": (HIGH, "Only an explicit publicNetworkAccess=Enabled fires; severity bumps to high when defaultAction=Allow is also explicit."),
    "azure_key_vault_purge_protection_disabled": (HIGH, "Only an explicit enablePurgeProtection=false fires; missing/unknown is skipped."),
    "azure_key_vault_soft_delete_disabled": (HIGH, "Only an explicit enableSoftDelete=false fires; missing/unknown is skipped."),
    "azure_key_vault_rbac_disabled": (MEDIUM, "Fires only when enableRbacAuthorization=false AND access_policy_count > 0; vaults with no access policies are not flagged."),
    # Azure — M77C
    "azure_role_assignment_broad_privilege": (HIGH, "Fires only when role_definition_name is a known broad built-in role (Owner/Contributor/User Access Administrator) resolved from a static GUID map, AND scope_type is subscription or resource_group."),
    "azure_app_service_https_disabled": (HIGH, "Only an explicit httpsOnly=false on the App Service fires; missing/unknown is skipped."),
    "azure_app_service_ftp_enabled": (HIGH, "Only an explicit ftpsState=AllAllowed fires; FtpsOnly and Disabled do not fire."),
    "azure_app_service_weak_tls": (HIGH, "Only explicit minTlsVersion='1.0' or '1.1' fires; missing/unknown is skipped."),
    "azure_app_service_public_network_access": (HIGH, "Only an explicit publicNetworkAccess=Enabled/true fires; missing/unknown is skipped."),
    "azure_sql_public_network_access": (HIGH, "Only an explicit publicNetworkAccess=Enabled fires; severity bumps to high when has_allow_azure_services_rule=true."),
    "azure_sql_weak_tls": (HIGH, "Only explicit minimalTlsVersion='1.0' or '1.1' fires; missing/unknown is skipped."),
    "azure_aks_local_accounts_enabled": (HIGH, "Only an explicit disableLocalAccounts=false fires; missing/unknown is skipped."),
    "azure_aks_public_api_access": (HIGH, "Fires only when private_cluster_enabled=false AND api_server_authorized_ip_range_count=0; partial data (None count) is not flagged."),
    "azure_aks_network_policy_missing": (MEDIUM, "Fires when network_policy is absent or 'none'; absence of a network policy is the default state so medium confidence is used."),
    # Google Cloud — M78B
    "google_cloud_iam_public_member": (HIGH, "Only an explicit allUsers / allAuthenticatedUsers sentinel binding on the project IAM policy fires; member identities are never read."),
    "google_cloud_iam_broad_privileged_role": (HIGH, "Only a curated set of broad project-level role names (roles/owner, roles/editor, roles/iam.securityAdmin, roles/resourcemanager.projectIamAdmin, roles/iam.serviceAccountAdmin, roles/iam.serviceAccountKeyAdmin) fires."),
    "google_cloud_firewall_public_admin_ingress": (HIGH, "Only INGRESS+allow rules with a 0.0.0.0/0 or ::/0 source range on a known admin/database/cache/search port fire; disabled rules are skipped."),
    "google_cloud_firewall_public_broad_ingress": (HIGH, "Only INGRESS+allow rules with a 0.0.0.0/0 or ::/0 source range that also cover all ports (or the 'all' protocol) fire; disabled rules are skipped."),
    "google_cloud_firewall_rule_no_targets": (MEDIUM, "Fires only when an INGRESS+allow rule from a public source range has target_tag_count=0 AND target_service_account_count=0; severity bumps to high when the same rule is also a broad/admin public ingress."),
    "google_cloud_storage_public_access_prevention_disabled": (HIGH, "Only fires when public_access_prevention is missing/inherited/unspecified or any value other than 'enforced'; severity bumps to high when uniform bucket-level access is also disabled."),
    "google_cloud_storage_uniform_access_disabled": (HIGH, "Only an explicit uniform_bucket_level_access_enabled=false fires; missing/unknown is skipped."),
    "google_cloud_storage_versioning_disabled": (HIGH, "Only an explicit versioning_enabled=false fires; missing/unknown is skipped."),
    "google_cloud_storage_retention_not_locked": (MEDIUM, "Fires when no retention policy is set OR retention_policy_locked is explicitly false; missing locked-state with no retention period is treated conservatively."),
    # Google Cloud — M78C: Cloud SQL
    "google_cloud_sql_public_network_access": (HIGH, "Only an explicit public_ip_enabled=true fires; severity is high when authorized_network_count > 0, medium otherwise."),
    "google_cloud_sql_weak_tls": (HIGH, "Only an explicit require_ssl=false or ssl_mode in {ALLOW_UNENCRYPTED_AND_ENCRYPTED, ENCRYPTED_ONLY} fires; missing/unknown is skipped."),
    "google_cloud_sql_backups_disabled": (HIGH, "Only an explicit backup_enabled=false fires; missing/unknown is skipped."),
    "google_cloud_sql_deletion_protection_disabled": (HIGH, "Only an explicit deletion_protection_enabled=false fires; missing/unknown is skipped."),
    # Google Cloud — M78C: Cloud Run
    "google_cloud_run_public_invoker": (HIGH, "Only fires when the IAM policy for the Cloud Run service has allUsers or allAuthenticatedUsers on roles/run.invoker; inferred from invoker policy counts."),
    "google_cloud_run_all_ingress": (HIGH, "Only an explicit ingress=INGRESS_TRAFFIC_ALL fires; internal/load-balancer ingress does not fire."),
    # Google Cloud — M78C: GKE
    "google_cloud_gke_public_control_plane": (HIGH, "Fires only when public_endpoint_enabled=true AND master_authorized_networks_count is 0 or absent; clusters with authorized networks are not flagged."),
    "google_cloud_gke_legacy_abac_enabled": (HIGH, "Only an explicit legacy_abac_enabled=true fires; missing/unknown is skipped."),
    "google_cloud_gke_network_policy_disabled": (MEDIUM, "Only an explicit network_policy_enabled=false fires; missing/unknown (absence of network policy is common) uses medium confidence."),
    "google_cloud_gke_workload_identity_disabled": (MEDIUM, "Fires when workload_identity_enabled=false (no workloadPool configured); absence of workload identity is the default cluster state."),
    # Google Cloud — M78C: Service account keys
    "google_cloud_service_account_user_managed_keys": (HIGH, "Only fires when user_managed_key_count > 0 on the project-level summary record; SA emails and key IDs are never read."),
    "google_cloud_service_account_old_keys": (HIGH, "Only fires when old_user_managed_key_count > 0 or oldest_key_age_days >= 90; computed from validAfterTime timestamps only."),
    # Google Cloud — M78C: Secret Manager
    "google_cloud_secret_manager_auto_replication_without_cmek": (MEDIUM, "Fires only when automatic_replication_count > 0 AND customer_managed_encryption_count == 0; secret names and values are never read."),
    # Twilio — M79B
    "twilio_phone_number_sms_webhook_missing": (HIGH, "Only fires when capability_sms=true AND sms_url_configured=false on a twilio_incoming_phone_number record; missing/unknown is skipped."),
    "twilio_phone_number_voice_webhook_missing": (HIGH, "Only fires when capability_voice=true AND voice_url_configured=false on a twilio_incoming_phone_number record; missing/unknown is skipped."),
    "twilio_phone_number_status_callback_missing": (MEDIUM, "Fires when capability_sms or capability_voice is set AND status_callback_configured=false; phone numbers with neither capability are not flagged."),
    "twilio_messaging_service_inbound_webhook_missing": (HIGH, "Only fires when inbound_request_url_configured=false AND use_inbound_webhook_on_number is not true; services using number-level webhooks are excluded."),
    "twilio_messaging_service_fallback_missing": (MEDIUM, "Fires when fallback_url_configured=false; absence of a fallback URL is the default state so medium confidence is used."),
    "twilio_messaging_service_status_callback_missing": (MEDIUM, "Fires when status_callback_url_configured=false; absence of a status callback is the common default."),
    "twilio_verify_short_code_length": (HIGH, "Only fires when code_length is an explicit integer < 6; missing/unknown values are skipped."),
    "twilio_verify_lookup_disabled": (MEDIUM, "Only an explicit lookup_enabled=false fires; missing/unknown is skipped."),
    "twilio_account_suspended": (MEDIUM, "Fires when account status is not 'active' or empty; missing/unknown is skipped."),
    # Twilio — M79C
    "twilio_api_key_stale": (MEDIUM, "Fires when date_updated or date_created indicates the key is 180+ days old; keys with no date metadata are skipped. Long-lived read-only keys may fire intentionally."),
    "twilio_messaging_service_observability_gap": (HIGH, "Only fires when both fallback_url_configured=false AND status_callback_url_configured=false are simultaneously true on a twilio_messaging_service record."),
    "twilio_messaging_service_number_level_inbound_webhook": (MEDIUM, "Fires when use_inbound_webhook_on_number=true AND inbound_request_url_configured=false; number-level delegation is a valid but fragmented pattern."),
    "twilio_messaging_service_long_validity_period": (MEDIUM, "Only fires when validity_period is an explicit integer > 86400; missing/unknown values are skipped."),
    "twilio_phone_number_messaging_observability_gap": (HIGH, "Only fires when capability_sms=true AND both sms_url_configured=false AND status_callback_configured=false on a twilio_incoming_phone_number record."),
    "twilio_phone_number_voice_observability_gap": (HIGH, "Only fires when capability_voice=true AND both voice_url_configured=false AND status_callback_configured=false on a twilio_incoming_phone_number record."),
    "twilio_verify_psd2_disabled": (MEDIUM, "Only an explicit psd2_enabled=false fires; missing/unknown is skipped. PSD2 is only relevant for financial transaction verification in regulated markets."),
    "twilio_verify_sms_to_landlines_allowed": (MEDIUM, "Only an explicit skip_sms_to_landlines=false fires; missing/unknown is skipped."),
    # SendGrid — M80B
    "sendgrid_api_key_broad_scopes": (HIGH, "Only fires when has_full_access=true on a sendgrid_api_key record; missing/false is never flagged."),
    "sendgrid_sender_identity_unverified": (HIGH, "Only fires when verified=false on a sendgrid_sender_identity record; missing/unknown is skipped."),
    "sendgrid_sender_identity_locked": (HIGH, "Only fires when locked=true on a sendgrid_sender_identity record; unlocked identities are not flagged."),
    "sendgrid_domain_authentication_invalid": (HIGH, "Only fires when valid=false on a sendgrid_domain_authentication record; missing/unknown is skipped."),
    "sendgrid_domain_automatic_security_disabled": (HIGH, "Only fires when automatic_security=false on a sendgrid_domain_authentication record; missing/unknown is skipped."),
    "sendgrid_domain_authentication_legacy": (HIGH, "Only fires when legacy=true on a sendgrid_domain_authentication record; non-legacy domains are not flagged."),
    "sendgrid_spam_check_disabled": (HIGH, "Only fires when spam_check_enabled=false on a sendgrid_mail_settings record; missing/unknown is skipped."),
    "sendgrid_sandbox_mode_enabled": (HIGH, "Only fires when sandbox_mode_enabled=true on a sendgrid_mail_settings record; disabled sandbox mode is not flagged."),
    "sendgrid_bcc_enabled": (HIGH, "Only fires when bcc_enabled=true on a sendgrid_mail_settings record; the BCC address is never stored."),
    "sendgrid_click_tracking_enabled": (HIGH, "Only fires when click_tracking_enabled=true on a sendgrid_tracking_settings record; disabled tracking is not flagged."),
    "sendgrid_open_tracking_enabled": (HIGH, "Only fires when open_tracking_enabled=true on a sendgrid_tracking_settings record; disabled tracking is not flagged."),
    "sendgrid_subscription_tracking_disabled": (HIGH, "Only fires when subscription_tracking_enabled=false on a sendgrid_tracking_settings record; missing/unknown is skipped."),
    "sendgrid_event_webhook_disabled": (HIGH, "Only fires when event_webhook_enabled=false on a sendgrid_webhook_settings record; missing/unknown is skipped."),
    "sendgrid_event_webhook_url_missing": (HIGH, "Only fires when event_webhook_enabled=true AND event_webhook_has_url=false on a sendgrid_webhook_settings record; both conditions must be explicitly present."),
    "sendgrid_suppression_settings_empty": (MEDIUM, "Only fires when suppression_group_count is an explicit integer equal to 0; missing/unknown suppression_group_count is skipped."),
    # SendGrid — M80C
    "sendgrid_sender_identity_reply_domain_mismatch": (HIGH, "Only fires when both from_email_domain and reply_to_domain are non-empty strings on a sendgrid_sender_identity record and they differ; missing/empty domains are never flagged. Domain strings only — full email addresses NEVER stored."),
    "sendgrid_domain_dns_records_missing": (HIGH, "Only fires when dns_record_count is an explicit integer equal to 0 on a sendgrid_domain_authentication record; missing/unknown counts are skipped. Raw DNS values NEVER stored."),
    "sendgrid_default_domain_authentication_invalid": (HIGH, "Only fires when default=true AND valid=false on a sendgrid_domain_authentication record; both conditions must be explicitly present."),
    "sendgrid_footer_disabled": (HIGH, "Only fires when footer_enabled=false on a sendgrid_mail_settings record; footer text content is NEVER stored."),
    "sendgrid_bounce_purge_disabled": (HIGH, "Only fires when bounce_purge_enabled=false on a sendgrid_mail_settings record; missing/unknown is skipped."),
    "sendgrid_template_engine_enabled": (HIGH, "Only fires when template_enabled=true on a sendgrid_mail_settings record; template content is NEVER stored."),
    "sendgrid_google_analytics_tracking_enabled": (HIGH, "Only fires when ganalytics_enabled=true on a sendgrid_tracking_settings record; GA parameter values and campaign data NEVER stored."),
    "sendgrid_event_webhook_broad_event_stream": (MEDIUM, "Only fires when event_webhook_enabled=true AND event_count > 8 on a sendgrid_webhook_settings record; event payloads and recipient data NEVER stored."),
    "sendgrid_inbound_parse_enabled": (HIGH, "Only fires when inbound_parse_enabled=true on a sendgrid_webhook_settings record; hostname, URL, email bodies, and recipient data NEVER stored."),
    "sendgrid_inbound_parse_raw_email_enabled": (HIGH, "Only fires when inbound_parse_enabled=true AND inbound_parse_send_raw_enabled=true; raw email content and recipient data NEVER stored."),
    "sendgrid_inbound_parse_spam_check_disabled": (HIGH, "Only fires when inbound_parse_enabled=true AND inbound_parse_spam_check_enabled=false; both conditions must be explicitly present."),
    # Auth0 — M81B
    "auth0_tenant_session_lifetime_extended": (HIGH, "Only fires when session_lifetime_category=='extended' on an auth0_tenant_settings record; no token or session content is stored."),
    "auth0_tenant_idle_session_lifetime_extended": (HIGH, "Only fires when idle_session_lifetime_category=='extended' on an auth0_tenant_settings record."),
    "auth0_tenant_dynamic_client_registration_enabled": (HIGH, "Only fires when flag_enable_dynamic_client_registration=true on an auth0_tenant_settings record."),
    "auth0_application_no_callbacks": (MEDIUM, "Only fires when callbacks_count==0 AND app_type is a web-based application (spa/regular_web); CLI/M2M/native apps are skipped. Raw callback URLs are never stored."),
    "auth0_application_many_callbacks": (HIGH, "Only fires when callbacks_count exceeds a conservative threshold; raw URLs NEVER stored."),
    "auth0_application_many_allowed_origins": (HIGH, "Only fires when (allowed_origins_count + web_origins_count) exceeds a conservative threshold; raw origin strings NEVER stored."),
    "auth0_application_oidc_non_conformant": (HIGH, "Only fires when oidc_conformant is explicitly false on an auth0_application record."),
    "auth0_application_weak_jwt_algorithm": (HIGH, "Only fires when jwt_alg is HS256/HS384/HS512/none; signing keys NEVER stored."),
    "auth0_refresh_token_rotation_disabled": (MEDIUM, "Only fires when refresh_token_rotation_enabled is false AND the application's grant_types_summary includes 'refresh_token'; CLI/M2M apps without refresh tokens are skipped."),
    "auth0_refresh_token_lifetime_extended": (HIGH, "Only fires when refresh_token_lifetime_category=='extended' on an auth0_application record."),
    "auth0_connection_no_enabled_clients": (HIGH, "Only fires when enabled_clients_count==0 on an auth0_connection record."),
    "auth0_connection_weak_password_policy": (MEDIUM, "Only fires for strategy=='auth0' database connections when password_policy_category is 'none'/'low'/'fair' or not configured; non-database connections are skipped. Connection credentials NEVER stored."),
    "auth0_resource_server_offline_access_enabled": (HIGH, "Only fires when allow_offline_access=true on an auth0_resource_server record."),
    "auth0_resource_server_token_lifetime_extended": (HIGH, "Only fires when token_lifetime_category=='extended' on an auth0_resource_server record."),
    "auth0_resource_server_rbac_disabled": (HIGH, "Only fires when rbac_enabled is explicitly false on an auth0_resource_server record."),
    "auth0_rule_disabled": (MEDIUM, "Only fires when enabled is explicitly false AND script_present=true on an auth0_rule record; rule script content NEVER stored."),
    "auth0_rule_large_script": (HIGH, "Only fires when script_length_category=='long' on an auth0_rule record; script content NEVER stored."),
    "auth0_action_not_deployed": (HIGH, "Only fires when deployed_version_present is false on an auth0_action record."),
    "auth0_action_secrets_present": (HIGH, "Only fires when secrets_count > 0 on an auth0_action record; secret names and values NEVER stored."),
    "auth0_mfa_factor_disabled": (HIGH, "Only fires for strong second factors (otp / webauthn-roaming / push-notification) when enabled is explicitly false; no enrollment data ever stored."),
    "auth0_custom_domain_not_ready": (HIGH, "Only fires when status is 'pending_verification'/'provisioning'/'disabled' on an auth0_custom_domain record; custom domain name strings NEVER stored."),
    "auth0_custom_domain_weak_tls_policy": (HIGH, "Only fires when tls_policy_category=='compatible' on an auth0_custom_domain record."),
    # Auth0 — M81C OAuth/application risk expansion
    "auth0_application_password_grant_enabled": (HIGH, "Only fires when grant_password_enabled=true on an auth0_application record; no credential values are stored."),
    "auth0_application_implicit_grant_enabled": (HIGH, "Only fires when grant_implicit_enabled=true on an auth0_application record."),
    "auth0_application_public_client_credentials_enabled": (HIGH, "Only fires when grant_client_credentials_enabled=true AND app_type is spa/native OR token_endpoint_auth_method=none; no client secret is stored."),
    "auth0_application_refresh_grant_without_rotation": (HIGH, "Only fires when grant_refresh_token_enabled=true AND refresh_token_rotation_enabled is explicitly false; no token values are stored."),
    "auth0_application_many_grant_types": (HIGH, "Only fires when grant_types_count exceeds the conservative threshold; no token values are stored."),
    "auth0_application_device_code_grant_enabled": (HIGH, "Only fires when grant_device_code_enabled=true on an auth0_application record."),
    "auth0_application_wildcard_callback": (HIGH, "Only fires when wildcard_callback_present=true (a boolean derived from callbacks during normalization); raw callback URLs are NEVER stored."),
    "auth0_application_wildcard_allowed_origin": (HIGH, "Only fires when wildcard_allowed_origin_present=true (a boolean derived from allowed_origins during normalization); raw origin URLs are NEVER stored."),
    "auth0_application_wildcard_logout_url": (HIGH, "Only fires when wildcard_logout_url_present=true (a boolean derived from allowed_logout_urls during normalization); raw logout URLs are NEVER stored."),
    "auth0_application_localhost_callback": (HIGH, "Only fires when localhost_callback_present=true (a boolean derived from callbacks during normalization); raw callback URLs are NEVER stored."),
    "auth0_application_localhost_origin": (HIGH, "Only fires when localhost_origin_present=true (a boolean derived from allowed_origins during normalization); raw origin URLs are NEVER stored."),
    "auth0_application_callback_missing_https": (HIGH, "Only fires when callbacks_missing_https=true (a boolean derived from callbacks during normalization, excluding localhost); raw callback URLs are NEVER stored."),
    "auth0_application_origin_missing_https": (HIGH, "Only fires when allowed_origins_missing_https=true (a boolean derived from allowed_origins during normalization, excluding localhost); raw origin URLs are NEVER stored."),
    "auth0_public_client_refresh_tokens_enabled": (MEDIUM, "Only fires when grant_refresh_token_enabled=true AND app_type is spa/native; no token values are stored."),
    "auth0_application_token_endpoint_auth_none": (HIGH, "Only fires when token_endpoint_auth_method=='none' on an auth0_application record."),
    # Datadog — M82B core security rules
    "datadog_monitor_disabled": (HIGH, "Only fires when enabled is explicitly false on a datadog_monitor record; raw query and message NEVER stored."),
    "datadog_monitor_unrestricted_roles": (MEDIUM, "Fires when restricted_roles_count==0; many monitors are intentionally open, so medium confidence applies."),
    "datadog_monitor_notify_no_data_disabled": (MEDIUM, "Only fires when notify_no_data is explicitly false; absence of no-data notification is common and may be intentional."),
    "datadog_monitor_long_query": (MEDIUM, "Only fires when query_complexity_category=='long'; raw query content NEVER stored."),
    "datadog_slo_no_monitors": (HIGH, "Only fires for slo_type=='monitor' SLOs where monitor_count==0; other SLO types are not flagged."),
    "datadog_slo_low_target": (MEDIUM, "Fires when target_category=='below_95'; a low target may be a business decision rather than a misconfiguration."),
    "datadog_dashboard_public_url_present": (HIGH, "Only fires when public_url_present=true on a datadog_dashboard record; the URL string NEVER stored."),
    "datadog_dashboard_unrestricted_roles": (MEDIUM, "Fires when restricted_roles_count==0; dashboards are commonly open within an organization."),
    "datadog_webhook_without_secret_headers": (HIGH, "Only fires when url_present=true AND secret_headers_present=false; webhook URL and header values NEVER stored."),
    "datadog_webhook_payload_template_present": (MEDIUM, "Only fires when payload_template_present=true; template content NEVER stored."),
    "datadog_notification_integration_no_channels": (MEDIUM, "Fires when enabled=true AND handle_count==0 AND channel_count==0; destination handles NEVER stored."),
    "datadog_application_key_broad_scopes": (HIGH, "Only fires when scopes_count exceeds the conservative threshold; scope names and key values NEVER stored."),
    "datadog_api_key_disabled": (HIGH, "Only fires when disabled=true on a datadog_api_key_metadata record; key values NEVER stored."),
    "datadog_role_high_permission_count": (HIGH, "Only fires when permission_count exceeds the conservative threshold; user identities NEVER stored."),
    "datadog_team_no_members": (HIGH, "Only fires when member_count==0 on a datadog_team record; member identities NEVER stored."),
    "datadog_cloud_integration_broad_collection": (HIGH, "Fires only when all three collection flags (resource, metric, log) are simultaneously true; account IDs NEVER stored."),
    "datadog_cloud_integration_log_collection_enabled": (HIGH, "Only fires when log_collection_enabled=true; log content and account IDs NEVER stored."),
    # Datadog — M82C monitor/webhook risk expansion
    "datadog_monitor_no_notifications": (HIGH, "Fires when notification_routing_present=false, derived from absence of @ in message before discarding; raw message NEVER stored."),
    "datadog_monitor_message_template_present": (MEDIUM, "Fires when message_template_present=true ({{ in message), derived before discarding; raw message NEVER stored. Very common — medium confidence."),
    "datadog_monitor_no_warning_threshold": (HIGH, "Fires only when threshold_critical_present=true AND threshold_warning_present=false; raw threshold values NEVER stored."),
    "datadog_monitor_no_recovery_threshold": (HIGH, "Fires only when threshold_critical_present=true AND threshold_recovery_present=false; raw threshold values NEVER stored."),
    "datadog_monitor_silenced_scopes_present": (HIGH, "Fires when silenced_scope_count > 0, derived from the silenced dict before discarding; scope identifiers NEVER stored."),
    "datadog_monitor_notify_audit_disabled": (MEDIUM, "Fires when notify_audit=false; audit notifications are commonly disabled, so medium confidence applies."),
    "datadog_monitor_require_full_window_disabled": (MEDIUM, "Fires when require_full_window=false; this is the default for many monitor types, so medium confidence applies."),
    "datadog_monitor_query_wildcard_scope": (HIGH, "Fires when query_uses_wildcard_scope=true ({*} present in query), derived before discarding; raw query NEVER stored."),
    "datadog_monitor_broad_group_by": (HIGH, "Fires when query_group_by_count >= 3, derived by counting 'by {' occurrences before discarding; raw query NEVER stored."),
    "datadog_monitor_long_no_data_timeframe": (HIGH, "Fires when no_data_timeframe_category=='extended' (>= 2 hours), derived before discarding; raw timeframe value categorised only."),
    "datadog_webhook_custom_headers_without_secret_headers": (HIGH, "Fires when custom_headers_present=true AND secret_headers_present=false; header names and values NEVER stored."),
    "datadog_webhook_large_payload_template": (MEDIUM, "Fires when payload_template_length_category=='long'; template content NEVER stored. Large templates are not inherently risky — medium confidence."),
    "datadog_webhook_auth_material_present": (HIGH, "Fires when auth_material_present=true, derived by checking header key names for auth patterns before discarding; header names and values NEVER stored."),
    "datadog_webhook_non_https_endpoint": (HIGH, "Fires when url_scheme_category=='http', derived from URL before discarding; URL string NEVER stored."),
    # Clerk — M83B core security rules
    "clerk_instance_mfa_disabled": (HIGH, "Only fires when mfa_enabled is explicitly false on a clerk_instance_settings record."),
    "clerk_instance_password_without_mfa": (HIGH, "Only fires when password_enabled=true AND mfa_enabled=false on a clerk_instance_settings record."),
    "clerk_instance_sign_up_enabled": (HIGH, "Only fires when sign_up_enabled=true on a clerk_instance_settings record; does not assert unauthorized access."),
    "clerk_application_mfa_not_required": (HIGH, "Only fires when mfa_required is explicitly false on a clerk_application record."),
    "clerk_domain_unverified": (HIGH, "Only fires when verified is explicitly false on a clerk_domain record; raw domain name strings are NEVER stored."),
    "clerk_domain_ssl_disabled": (HIGH, "Only fires when ssl_enabled is explicitly false on a clerk_domain record; raw domain name strings are NEVER stored."),
    "clerk_redirect_url_non_https": (HIGH, "Only fires when url_present=true AND url_scheme_category is not 'https' on a clerk_redirect_url_config record; raw URL strings are NEVER stored."),
    "clerk_redirect_url_wildcard_present": (HIGH, "Only fires when wildcard_present=true on a clerk_redirect_url_config record; raw URL strings are NEVER stored."),
    "clerk_redirect_url_localhost_present": (HIGH, "Only fires when localhost_present=true on a clerk_redirect_url_config record; raw URL strings are NEVER stored."),
    "clerk_jwt_template_custom_claims_present": (HIGH, "Only fires when custom_claims_present=true on a clerk_jwt_template record; claim names, values, and template body are NEVER stored."),
    "clerk_jwt_template_long_lifetime": (HIGH, "Only fires when lifetime_category is 'extended' or 'long' on a clerk_jwt_template record; no token values are stored."),
    "clerk_webhook_endpoint_disabled": (HIGH, "Only fires when enabled is explicitly false on a clerk_webhook_endpoint record; this is an integration reliability posture item."),
    "clerk_webhook_without_signing": (HIGH, "Only fires when url_present=true AND secret_present=false on a clerk_webhook_endpoint record; webhook URL and secret values are NEVER stored."),
    "clerk_webhook_non_https": (HIGH, "Only fires when url_present=true AND url_scheme_category is not 'https' on a clerk_webhook_endpoint record; webhook URL strings are NEVER stored."),
    "clerk_email_sms_custom_sender_present": (HIGH, "Only fires when custom_sender_present=true on a clerk_email_sms_settings record; sender addresses are NEVER stored."),
    "clerk_auth_strategy_mfa_not_required": (MEDIUM, "Only fires when mfa_enabled=true AND mfa_required=false on a clerk_auth_strategy record; optional MFA is a valid configuration — medium confidence."),
    "clerk_auth_strategy_password_without_mfa": (MEDIUM, "Only fires when password_enabled=true AND mfa_required=false on a clerk_auth_strategy record; connection credentials are NEVER stored."),
    "clerk_session_lifetime_extended": (HIGH, "Only fires when session_lifetime_category is 'extended' or 'very_long' on a clerk_session_policy record; no session token values are stored."),
    "clerk_session_inactivity_timeout_extended": (HIGH, "Only fires when inactivity_timeout_category=='extended' on a clerk_session_policy record; no session token values are stored."),
    "clerk_session_single_session_disabled": (HIGH, "Only fires when single_session_mode is explicitly false on a clerk_session_policy record; no session data is stored."),
    "clerk_session_token_rotation_disabled": (HIGH, "Only fires when token_rotation_enabled is explicitly false on a clerk_session_policy record; no token values are stored."),
    # Clerk — M83C auth/application risk expansion
    "clerk_application_sign_up_enabled": (HIGH, "Only fires when sign_up_enabled=true on a clerk_application record."),
    "clerk_application_password_without_mfa": (HIGH, "Only fires when password_enabled=true AND mfa_required=false on a clerk_application record."),
    "clerk_application_oauth_without_mfa": (HIGH, "Only fires when oauth_provider_count > 0 AND mfa_required=false on a clerk_application record; count ONLY — no provider identities stored."),
    "clerk_application_saml_without_mfa": (HIGH, "Only fires when saml_enabled=true AND mfa_required=false on a clerk_application record; no SAML certificates or credentials stored."),
    "clerk_application_many_redirect_urls": (HIGH, "Only fires when redirect_url_count exceeds the conservative threshold; raw redirect URLs are NEVER stored."),
    "clerk_application_many_allowed_origins": (HIGH, "Only fires when allowed_origin_count exceeds the conservative threshold; raw origin strings are NEVER stored."),
    "clerk_redirect_url_custom_scheme_present": (HIGH, "Only fires when custom_scheme_present=true on a clerk_redirect_url_config record; raw URL strings are NEVER stored."),
    "clerk_jwt_template_audience_missing": (HIGH, "Only fires when audience_present is explicitly false on a clerk_jwt_template record; audience URI values are NEVER stored."),
    "clerk_jwt_template_issuer_missing": (HIGH, "Only fires when issuer_present is explicitly false on a clerk_jwt_template record; issuer URI values are NEVER stored."),
    "clerk_jwt_template_many_claims": (HIGH, "Only fires when claims_count exceeds the conservative threshold; claim names and values are NEVER stored."),
    "clerk_webhook_broad_event_scope": (HIGH, "Only fires when event_count exceeds the conservative threshold; event names are NEVER stored."),
    "clerk_org_verified_domains_not_required": (HIGH, "Only fires when organizations_enabled=true AND verified_domains_required=false on a clerk_organization_settings record."),
    "clerk_org_invitations_enabled": (HIGH, "Only fires when organizations_enabled=true AND invitation_enabled=true; member identities and invitation content are NEVER stored."),
    "clerk_org_admin_role_missing": (HIGH, "Only fires when organizations_enabled=true AND admin_role_present is explicitly false on a clerk_organization_settings record."),
    "clerk_org_high_role_count": (HIGH, "Only fires when role_count exceeds the conservative threshold; role names and member identities are NEVER stored."),
    "clerk_org_high_permission_count": (HIGH, "Only fires when permission_count exceeds the conservative threshold; permission names and member identities are NEVER stored."),
    "clerk_session_device_tracking_disabled": (HIGH, "Only fires when device_tracking_enabled is explicitly false on a clerk_session_policy record; no session data is stored."),
    "clerk_session_reverification_disabled": (HIGH, "Only fires when reverification_required is explicitly false on a clerk_session_policy record; no session token values are stored."),
    "clerk_session_long_lifetime_without_single_session": (HIGH, "Only fires when session_lifetime_category is extended/very_long AND single_session_mode is explicitly false; no session token values are stored."),
    # PagerDuty — M84B core security rules
    "pagerduty_service_no_escalation_policy": (HIGH, "Only fires when the normalized service record's escalation_policy_id is empty; no PagerDuty API tokens, routing keys, or incident data are stored."),
    "pagerduty_service_no_integrations": (HIGH, "Only fires when integration_count is exactly 0; no integration key or routing key values are stored."),
    "pagerduty_service_ack_timeout_disabled": (HIGH, "Only fires when acknowledgement_timeout_category is 'disabled' on the service record."),
    "pagerduty_service_auto_resolve_disabled": (MEDIUM, "Fires when auto_resolve_timeout_category is 'disabled'; some teams intentionally disable auto-resolve for high-severity services."),
    "pagerduty_service_alert_creation_limited": (MEDIUM, "Fires when alert_creation_category is 'incidents_only'; some teams intentionally route alerts as incidents only for low-volume services."),
    "pagerduty_service_no_teams": (MEDIUM, "Fires when team_count is exactly 0; no team member identities are stored."),
    "pagerduty_escalation_policy_no_rules": (HIGH, "Only fires when escalation_rule_count is exactly 0; no user targets, emails, or contact methods are stored."),
    "pagerduty_escalation_policy_single_level": (MEDIUM, "Fires when escalation_level_count is <=1 and escalation_rule_count is >0; some on-call rotations are intentionally single-level."),
    "pagerduty_schedule_no_layers": (HIGH, "Only fires when layer_count is exactly 0 on a schedule record; no user identities are stored."),
    "pagerduty_schedule_no_teams": (MEDIUM, "Fires when team_count is exactly 0; no team member identities are stored."),
    "pagerduty_service_integration_missing_key_indicator": (HIGH, "Only fires when has_integration_key is explicitly false; the integration key value itself is never stored."),
    "pagerduty_service_integration_email_type": (MEDIUM, "Fires when type_category is 'email'; some teams intentionally use email-based ingestion for low-priority alerts."),
    "pagerduty_webhook_subscription_inactive": (HIGH, "Only fires when active is explicitly false on a webhook subscription record."),
    "pagerduty_webhook_subscription_non_https": (HIGH, "Only fires when delivery_url_scheme_category is a non-https, non-absent scheme (e.g. 'http' or 'other'); the URL value is never stored."),
    "pagerduty_webhook_subscription_broad_event_scope": (MEDIUM, "Fires when event_count is >10; some intentionally broad observability webhooks subscribe to many event types."),
    "pagerduty_event_orchestration_no_routes": (HIGH, "Only fires when route_count is exactly 0 on an event orchestration record; routing rule expressions are never stored."),
    "pagerduty_event_orchestration_no_team": (MEDIUM, "Fires when team_present is explicitly false."),
    "pagerduty_business_service_no_team": (MEDIUM, "Fires when team_present is explicitly false on a business service."),
    "pagerduty_business_service_no_contact": (MEDIUM, "Fires when point_of_contact_present is explicitly false; the contact name or identity is never stored."),
    "pagerduty_response_play_no_responders": (HIGH, "Only fires when responder_count is exactly 0; no responder identities are stored."),
    "pagerduty_response_play_no_subscribers": (MEDIUM, "Fires when subscriber_count is exactly 0; some plays intentionally have no subscribers."),
    "pagerduty_response_play_not_runnable": (MEDIUM, "Fires when runnability is 'unknown'; some response plays may be intentionally restricted."),
    # PagerDuty — M84C escalation/webhook risk expansion
    "pagerduty_escalation_policy_no_targets": (HIGH, "Only fires when escalation_rule_count > 0 AND target_count is exactly 0; no target IDs or identities are stored."),
    "pagerduty_escalation_policy_low_target_count": (HIGH, "Only fires when 0 < target_count <= 1 across all escalation rules; no target identities are stored."),
    "pagerduty_escalation_policy_no_schedule_targets": (MEDIUM, "Fires when rule_count > 0 AND target_count > 0 AND schedule_target_count is 0; user-only targets are a common valid config for small teams."),
    "pagerduty_escalation_policy_no_team_targets": (MEDIUM, "Fires when team_count is exactly 0 on the escalation policy; no team member identities are stored."),
    "pagerduty_schedule_no_targets": (HIGH, "Only fires when layer_count > 0 AND user_count is exactly 0; no user identities are stored."),
    "pagerduty_schedule_low_target_count": (HIGH, "Only fires when user_count is exactly 1; no user identities are stored."),
    "pagerduty_schedule_single_layer": (MEDIUM, "Fires when layer_count is exactly 1; single-layer schedules may be intentional for small teams."),
    "pagerduty_schedule_no_restrictions": (MEDIUM, "Fires when layer_count > 0 AND restriction_count is 0; 24/7 coverage without restrictions is sometimes intentional."),
    "pagerduty_service_integration_routing_key_missing": (HIGH, "Only fires when type_category is 'generic_events_api' AND routing_key_present is explicitly false; routing key values are never stored."),
    "pagerduty_service_integration_unknown_type": (MEDIUM, "Fires when type_category is 'other' (unrecognized type); some custom integrations may legitimately use non-standard types."),
    "pagerduty_webhook_subscription_no_events": (HIGH, "Only fires when event_count is exactly 0; event type names are never stored."),
    "pagerduty_webhook_subscription_secret_not_indicated": (MEDIUM, "Fires when active=True AND has_custom_headers is False; some endpoints rely on network-level security instead of header auth."),
    "pagerduty_webhook_subscription_broad_scope_high": (HIGH, "Only fires when event_count exceeds the high threshold (>20); event type names are never stored."),
    "pagerduty_webhook_subscription_account_scope": (MEDIUM, "Fires when filter_type is 'account'; account-scoped webhooks are sometimes intentional for observability integrations."),
    "pagerduty_event_orchestration_low_route_count": (MEDIUM, "Fires when route_count is exactly 1; minimal routing may be intentional for simple orchestrations."),
    "pagerduty_response_play_low_responder_count": (HIGH, "Only fires when responder_count is exactly 1; no responder identities are stored."),
    "pagerduty_response_play_no_team": (MEDIUM, "Fires when team_present is explicitly false on a response play record."),
    "pagerduty_response_play_manual_only": (MEDIUM, "Fires when runnability is 'owner'; owner-only runnability may be intentional for sensitive response plays."),
    # Linear — M85B core security rules
    "linear_workspace_missing_url_key": (HIGH, "Only fires when url_key_present is explicitly false on a linear_workspace record; missing/unknown is skipped."),
    "linear_workspace_missing_logo": (HIGH, "Only fires when logo_present is explicitly false on a linear_workspace record; missing/unknown is skipped."),
    "linear_team_private": (HIGH, "Only fires when private_team is explicitly true on a linear_team record; public teams are not flagged."),
    "linear_team_low_member_count": (HIGH, "Only fires when member_count_category is 'none' on a linear_team record; teams with any members are not flagged."),
    "linear_team_no_projects": (HIGH, "Only fires when project_count is exactly 0 on a linear_team record."),
    "linear_team_auto_archive_disabled": (HIGH, "Only fires when auto_archive_enabled is explicitly false on a linear_team record; presence of an auto-archive period is treated as enabled."),
    "linear_team_cycles_disabled": (HIGH, "Only fires when cycle_enabled is explicitly false on a linear_team record."),
    "linear_team_long_cycle_duration": (HIGH, "Only fires when cycle_duration_category is 'long' (>14 days) on a linear_team record."),
    "linear_project_no_lead": (HIGH, "Only fires when lead_present is explicitly false on a linear_project record; lead identity is never stored."),
    "linear_project_no_members": (HIGH, "Only fires when member_count_category is 'none' on a linear_project record; member identities are never stored."),
    "linear_project_high_issue_count": (MEDIUM, "Fires when issue_count_category is 'many' (>50 issues); a large backlog may be intentional for some teams. Issue content is never stored."),
    "linear_project_unhealthy": (HIGH, "Only fires when project_health_category is 'atrisk' or 'offtrack' on a linear_project record; issue content is never stored."),
    "linear_project_unknown_status": (MEDIUM, "Fires when project_status_category is 'unknown'; custom status names may not be classified, so medium confidence is used."),
    "linear_workflow_state_unknown_type": (MEDIUM, "Fires when state_type_category is 'unknown'; custom state types may not map to standard Linear types, so medium confidence is used."),
    "linear_label_missing_team_scope": (HIGH, "Only fires when team_id is absent (None) on a linear_label record, indicating a workspace-wide label."),
    "linear_webhook_disabled": (HIGH, "Only fires when webhook_enabled is explicitly false on a linear_webhook record; webhook URL values are never stored."),
    "linear_webhook_no_secret_indicator": (HIGH, "Only fires when webhook_secret_present is explicitly false on a linear_webhook record; webhook secret values are never stored."),
    "linear_webhook_non_https": (HIGH, "Only fires when webhook_url_scheme_category is 'non_https' on a linear_webhook record; the URL value is never stored."),
    "linear_webhook_no_events": (HIGH, "Only fires when webhook_resource_types_count is exactly 0 on a linear_webhook record."),
    "linear_webhook_broad_resource_scope": (MEDIUM, "Fires when webhook_resource_types_count is >= 5; some webhooks intentionally subscribe to many resource types for observability purposes."),
    "linear_view_shared": (HIGH, "Only fires when view_shared is explicitly true on a linear_view record."),
    "linear_cycle_high_issue_count": (MEDIUM, "Fires when issue_count_category is 'many' (>50 issues); large cycles may be intentional for some teams. Issue content is never stored."),
    "linear_integration_disabled": (HIGH, "Only fires when integration_enabled is explicitly false on a linear_integration record; integration credentials are never stored."),
    "linear_integration_unknown_type": (MEDIUM, "Fires when integration_type_category is 'unknown'; some custom or newer integration types may not be recognized, so medium confidence is used."),
    # Linear — M85C workflow/webhook risk expansion
    "linear_workspace_low_team_count": (HIGH, "Only fires when team_count is an explicit integer <= 1 on a linear_workspace record; count is derived from organization query, never from team names/IDs."),
    "linear_workspace_no_webhooks": (HIGH, "Only fires when webhook_count is an explicit integer equal to 0, derived from the count of webhooks fetched for this workspace."),
    "linear_workspace_no_integrations": (MEDIUM, "Fires when integration_count is exactly 0; may under-report if integrations are plan-gated or inaccessible to the API key. Integration credentials are never stored."),
    "linear_team_no_backlog_state": (HIGH, "Only fires when has_backlog_state is explicitly false on a linear_team record; state names are never stored — only the type enum value is used."),
    "linear_team_no_started_state": (HIGH, "Only fires when has_started_state is explicitly false on a linear_team record; state names are never stored."),
    "linear_team_no_completed_state": (HIGH, "Only fires when has_completed_state is explicitly false on a linear_team record; state names are never stored."),
    "linear_team_no_canceled_state": (MEDIUM, "Fires when has_canceled_state is explicitly false; some teams intentionally omit a cancelled state — medium confidence."),
    "linear_team_low_workflow_state_count": (HIGH, "Only fires when workflow_state_count is an explicit integer <= 2; raw state names are never stored."),
    "linear_team_no_labels": (HIGH, "Only fires when label_count is an explicit integer equal to 0 on a linear_team record; label names are never stored."),
    "linear_team_no_webhooks": (HIGH, "Only fires when webhook_count is an explicit integer equal to 0 on a linear_team record; webhook URL values are never stored."),
    "linear_project_no_team_scope": (HIGH, "Only fires when team_count is an explicit integer equal to 0 on a linear_project record; team IDs and names are never stored."),
    "linear_webhook_issue_comment_scope": (HIGH, "Only fires when webhook_has_comment_type is explicitly true — a boolean derived from the resourceTypes list before discarding; raw resource type names are never stored."),
    "linear_webhook_attachment_scope": (HIGH, "Only fires when webhook_has_attachment_type is explicitly true — a boolean derived from the resourceTypes list before discarding; raw resource type names are never stored."),
    "linear_view_shared_without_team_scope": (HIGH, "Only fires when view_shared is explicitly true AND team_id is absent/None on a linear_view record."),
    "linear_integration_workspace_scoped": (MEDIUM, "Fires when integration_enabled=True AND team_id is absent/None; workspace-scoped integrations may be intentional for some service types."),
    # Jira core security rules — M86B
    "jira_site_missing_url": (HIGH, "Only fires when site_url_present is explicitly False on a jira_site record; the boolean is derived in the connector and never the raw URL."),
    "jira_site_no_projects": (HIGH, "Only fires when project_count == 0 on a jira_site record — a direct count from the Jira project search response."),
    "jira_site_no_webhooks": (HIGH, "Only fires when webhook_count == 0 on a jira_site record — a direct count from the Jira webhook list response."),
    "jira_site_no_automation_rules": (HIGH, "Only fires when automation_rule_count == 0 on a jira_site record — a direct count from the Jira automation API."),
    "jira_project_missing_key": (HIGH, "Only fires when project_key_present is explicitly False on a jira_project record; the raw key is never stored."),
    "jira_project_private": (MEDIUM, "Fires when project_private=True on a jira_project record; some projects are intentionally configured private for restricted access."),
    "jira_project_archived": (HIGH, "Only fires when project_archived=True on a jira_project record — derived from the Jira API archived flag."),
    "jira_project_deleted": (HIGH, "Only fires when project_deleted=True on a jira_project record — derived from the Jira API deleted flag."),
    "jira_project_simplified": (MEDIUM, "Fires when project_simplified=True on a jira_project record; some teams intentionally choose team-managed (simplified) projects."),
    "jira_project_unknown_type_category": (MEDIUM, "Fires when project_type_category is empty or 'unknown'; reflects a project type the connector could not classify rather than a confirmed misconfiguration."),
    "jira_project_unknown_style_category": (MEDIUM, "Fires when project_style_category is empty or 'unknown'; reflects a project style the connector could not classify rather than a confirmed misconfiguration."),
    "jira_project_no_boards": (HIGH, "Only fires when board_count == 0 on a jira_project record — a direct count from the connector."),
    "jira_project_no_issue_types": (HIGH, "Only fires when issue_type_count == 0 on a jira_project record — a direct count from the connector."),
    "jira_project_no_lead": (HIGH, "Only fires when lead_present=False on a jira_project record; the lead identity is never stored, only the presence boolean."),
    "jira_board_missing_project_link": (MEDIUM, "Fires when project_id is None on a jira_board record; some board types (e.g. user-scoped) legitimately lack a project association."),
    "jira_board_unknown_type_category": (MEDIUM, "Fires when board_type_category is empty or 'unknown'; reflects a board type the connector could not classify rather than a confirmed misconfiguration."),
    "jira_board_unknown_location_type": (MEDIUM, "Fires when board_location_type_category is 'unknown', 'global', or empty; broad location scope may be intentional for cross-team boards."),
    "jira_workflow_inactive": (HIGH, "Only fires when workflow_active=False on a jira_workflow record — a direct Jira API status flag."),
    "jira_workflow_no_statuses": (MEDIUM, "Fires when workflow_status_count <= 1; some single-status workflows are intentional placeholders."),
    "jira_workflow_no_transitions": (MEDIUM, "Fires when workflow_transition_count <= 1; sparse-transition workflows may be intentional for simple processes."),
    "jira_workflow_excessive_global_transitions": (MEDIUM, "Fires when workflow_global_transition_count == 0; many workflows intentionally avoid global transitions for governance reasons."),
    "jira_workflow_scheme_unused": (HIGH, "Only fires when workflow_scheme_project_count == 0 on a jira_workflow_scheme record."),
    "jira_workflow_scheme_no_default": (HIGH, "Only fires when workflow_scheme_default_present=False on a jira_workflow_scheme record."),
    "jira_permission_scheme_anonymous_grant": (HIGH, "Only fires when permission_anonymous_grant_count > 0 on a jira_permission_scheme record — a direct count of anonymous principal grants."),
    "jira_permission_scheme_anyone_grant": (HIGH, "Only fires when permission_anyone_grant_count > 0 on a jira_permission_scheme record — a direct count of 'anyone' principal grants."),
    "jira_permission_scheme_logged_in_grant": (HIGH, "Only fires when permission_logged_in_grant_count > 0 on a jira_permission_scheme record — a direct count of authenticated-user grants."),
    "jira_notification_scheme_email_recipients": (MEDIUM, "Fires when notification_email_recipient_count >= 10; broad notification fan-out may be intentional."),
    "jira_notification_scheme_group_recipients": (HIGH, "Only fires when notification_group_recipient_count > 0 on a jira_notification_scheme record."),
    "jira_notification_scheme_no_notifications": (HIGH, "Only fires when notification_count == 0 on a jira_notification_scheme record."),
    "jira_issue_type_scheme_no_default": (HIGH, "Only fires when default_issue_type_present=False on a jira_issue_type_scheme record."),
    "jira_issue_type_scheme_no_types": (MEDIUM, "Fires when issue_type_count <= 1; some schemes are intentionally narrowed to one issue type."),
    "jira_field_configuration_scheme_no_configurations": (MEDIUM, "Fires when required_field_count >= 20; large required-field counts may be intentional for compliance-heavy projects."),
    "jira_field_configuration_scheme_hidden_required_conflict": (MEDIUM, "Fires when hidden_field_count >= 20; large hidden-field counts may be intentional for simplified UIs."),
    "jira_screen_scheme_no_fields": (MEDIUM, "Fires when field_count >= 50; large field counts may be intentional for highly customized projects."),
    "jira_screen_scheme_no_screens": (HIGH, "Only fires when screen_count == 0 on a jira_screen_scheme record."),
    "jira_webhook_disabled": (HIGH, "Only fires when webhook_enabled=False on a jira_webhook record — a direct Jira API status flag."),
    "jira_webhook_no_secret_indicator": (HIGH, "Only fires when webhook_secret_present=False on a jira_webhook record; the raw secret is never stored."),
    "jira_webhook_non_https": (HIGH, "Only fires when webhook_url_present=True AND webhook_url_scheme_category='non_https'; the raw URL is never stored."),
    "jira_webhook_no_events": (HIGH, "Only fires when webhook_event_count == 0 on a jira_webhook record."),
    "jira_webhook_no_jql_filter": (MEDIUM, "Fires when webhook_jql_filter_present=False; some webhooks intentionally subscribe to all events without a JQL filter."),
    "jira_automation_rule_disabled": (HIGH, "Only fires when automation_enabled=False on a jira_automation_rule record — a direct Jira API status flag."),
    "jira_automation_rule_unknown_trigger": (MEDIUM, "Fires when automation_trigger_type_category is empty or 'unknown'; reflects a trigger the connector could not classify rather than a confirmed misconfiguration."),
    "jira_automation_rule_global_scope": (MEDIUM, "Fires when automation_scope_category is 'workspace', 'global', or 'all_projects'; workspace-scoped automation may be intentional for tenant-wide governance."),
    # Jira workflow/webhook risk expansion — M86C
    "jira_workflow_no_done_status": (HIGH, "Only fires when workflow_has_done_status=False on a jira_workflow record; the status category is derived, never the raw status name."),
    "jira_workflow_no_in_progress_status": (HIGH, "Only fires when workflow_has_in_progress_status=False on a jira_workflow record; the status category is derived, never the raw status name."),
    "jira_workflow_high_transition_rule_count": (MEDIUM, "Fires when workflow_transition_rule_count exceeds the conservative threshold; complex workflows may be intentional for governance-heavy processes."),
    "jira_workflow_high_validator_count": (MEDIUM, "Fires when workflow_validator_count exceeds the conservative threshold; many validators may be intentional for strict workflows."),
    "jira_workflow_high_condition_count": (MEDIUM, "Fires when workflow_condition_count exceeds the conservative threshold; many conditions may be intentional for strict workflows."),
    "jira_workflow_high_post_function_count": (MEDIUM, "Fires when workflow_post_function_count exceeds the conservative threshold; many post-functions may be intentional for automation-heavy workflows."),
    "jira_workflow_orphan_statuses": (HIGH, "Only fires when workflow_orphan_status_count > 0 on a jira_workflow record — a direct count of statuses with no inbound/outbound transition."),
    "jira_workflow_scheme_unmapped_issue_types": (HIGH, "Only fires when workflow_scheme_unmapped_issue_type_count > 0 on a jira_workflow_scheme record — a direct count of issue types not explicitly mapped to a workflow."),
    "jira_workflow_scheme_low_workflow_count": (HIGH, "Only fires when workflow_scheme_workflow_count < 1 on a jira_workflow_scheme record — a direct count."),
    "jira_workflow_scheme_high_issue_type_mapping_count": (MEDIUM, "Fires when workflow_scheme_issue_type_mapping_count exceeds the conservative threshold; many mappings may be intentional for large projects."),
    "jira_permission_scheme_public_browse_projects": (HIGH, "Only fires when permission_public_browse_projects=True on a jira_permission_scheme record — a direct derived boolean for a public grant on browse-projects."),
    "jira_permission_scheme_public_administer_projects": (HIGH, "Only fires when permission_public_administer_projects=True on a jira_permission_scheme record — a direct derived boolean for a public grant on administer-projects."),
    "jira_permission_scheme_public_manage_sprints": (HIGH, "Only fires when permission_public_manage_sprints=True on a jira_permission_scheme record — a direct derived boolean for a public grant on manage-sprints."),
    "jira_permission_scheme_public_create_issues": (HIGH, "Only fires when permission_public_create_issues=True on a jira_permission_scheme record — a direct derived boolean for a public grant on create-issues."),
    "jira_permission_scheme_public_transition_issues": (HIGH, "Only fires when permission_public_transition_issues=True on a jira_permission_scheme record — a direct derived boolean for a public grant on transition-issues."),
    "jira_permission_scheme_unknown_holder": (MEDIUM, "Fires when permission_unknown_holder_count > 0; reflects grant holder types the connector could not classify rather than a confirmed misconfiguration."),
    "jira_permission_scheme_high_privilege_grants": (MEDIUM, "Fires when permission_high_privilege_grant_count exceeds the conservative threshold; some broad high-privilege grants may be intentional."),
    "jira_permission_scheme_high_public_grant_count": (MEDIUM, "Fires when permission_public_grant_count exceeds the conservative threshold; some public grants may be intentional for open intake projects."),
    "jira_notification_scheme_unknown_recipients": (MEDIUM, "Fires when notification_unknown_recipient_count > 0; reflects recipient types the connector could not classify rather than a confirmed misconfiguration."),
    "jira_notification_scheme_high_event_count": (MEDIUM, "Fires when notification_event_count exceeds the conservative threshold; broad notification coverage may be intentional."),
    "jira_webhook_comment_event_scope": (HIGH, "Only fires when webhook_has_comment_events=True on a jira_webhook record — a direct derived boolean; the raw event list is never stored."),
    "jira_webhook_attachment_event_scope": (HIGH, "Only fires when webhook_has_attachment_events=True on a jira_webhook record — a direct derived boolean; the raw event list is never stored."),
    "jira_webhook_sprint_event_scope": (HIGH, "Only fires when webhook_has_sprint_events=True on a jira_webhook record — a direct derived boolean; the raw event list is never stored."),
    "jira_webhook_worklog_event_scope": (HIGH, "Only fires when webhook_has_worklog_events=True on a jira_webhook record — a direct derived boolean; the raw event list is never stored."),
    "jira_webhook_all_issue_events": (HIGH, "Only fires when webhook_all_issue_events=True on a jira_webhook record — a direct derived boolean for created+updated+deleted issue events; the raw event list is never stored."),
    "jira_automation_rule_web_request_action": (HIGH, "Only fires when automation_has_web_request_action=True on a jira_automation_rule record — a direct derived boolean; the request destination is never stored."),
    "jira_automation_rule_email_action": (HIGH, "Only fires when automation_has_email_action=True on a jira_automation_rule record — a direct derived boolean; recipients and content are never stored."),
    "jira_automation_rule_external_action": (HIGH, "Only fires when automation_has_external_action=True on a jira_automation_rule record — a direct derived boolean; the integration destination is never stored."),
    "jira_automation_rule_comment_action": (HIGH, "Only fires when automation_has_comment_action=True on a jira_automation_rule record — a direct derived boolean; comment content is never stored."),
    "jira_automation_rule_high_action_count": (MEDIUM, "Fires when automation_action_count exceeds the conservative threshold; complex automation rules may be intentional."),
    "jira_automation_rule_high_branch_count": (MEDIUM, "Fires when automation_branch_count exceeds the conservative threshold; branch-heavy automation rules may be intentional."),
    "jira_automation_rule_multi_project_scope": (MEDIUM, "Fires when automation_scope_category is 'multi-project'; multi-project automation may be intentional for shared governance."),
    "jira_automation_rule_unknown_scope": (MEDIUM, "Fires when automation_scope_category is empty or 'unknown'; reflects a scope the connector could not classify rather than a confirmed misconfiguration."),
    "jira_board_no_filter_indicator": (HIGH, "Only fires when board_filter_present=False on a jira_board record — a direct derived boolean."),
    "jira_board_broad_jql_filter": (MEDIUM, "Fires when board_jql_filter_broad=True; broad board filters may be intentional for cross-team boards. The raw JQL is never stored."),
    "jira_board_high_quick_filter_count": (MEDIUM, "Fires when board_quick_filter_count exceeds the conservative threshold; many quick filters may be intentional."),
    "jira_board_unknown_swimlane_strategy": (MEDIUM, "Fires when board_swimlane_strategy_category is empty or 'unknown'; reflects a strategy the connector could not classify rather than a confirmed misconfiguration."),
    "jira_board_no_columns": (HIGH, "Only fires when board_column_count < 1 on a jira_board record — a direct count."),
    "jira_screen_scheme_unmapped_screens": (HIGH, "Only fires when screen_unmapped_screen_count > 0 on a jira_screen_scheme record — a direct count of operation slots without a mapped screen."),
    # GitLab — M87B core security rules
    "gitlab_project_public_visibility": (HIGH, "Only fires when visibility_category is explicitly 'public' on a gitlab_project record — a direct category from the GitLab API."),
    "gitlab_project_shared_runners_enabled": (MEDIUM, "Fires when shared_runners_enabled=True on a non-public gitlab_project record; shared runners may be intentional for some projects."),
    "gitlab_project_snippets_enabled_public": (MEDIUM, "Fires when snippets_enabled=True on a public gitlab_project record; public snippet sharing may be intentional for open-source projects."),
    "gitlab_group_public_visibility": (HIGH, "Only fires when visibility_category is explicitly 'public' on a gitlab_group record — a direct category from the GitLab API."),
    "gitlab_branch_force_push_enabled": (HIGH, "Only fires when allow_force_push=True on a gitlab_branch_protection record — a direct boolean from the GitLab protected-branches API."),
    "gitlab_branch_code_owner_approval_missing": (MEDIUM, "Fires when code_owner_approval_required=False on a protected/default/wildcard branch rule; code owner approval may be managed via other controls."),
    "gitlab_webhook_secret_missing": (HIGH, "Only fires when secret_token_present=False on an active (enabled=True) gitlab_webhook record — a direct boolean derived in the connector."),
    "gitlab_webhook_ssl_verification_disabled": (HIGH, "Only fires when ssl_verification_enabled=False on an active (enabled=True) gitlab_webhook record — a direct boolean from the GitLab hooks API."),
    "gitlab_ci_unprotected_unmasked_variables": (HIGH, "Only fires when unprotected_unmasked_count > 0 on a gitlab_ci_variable_summary record — a direct count derived in the connector. CI variable names and values are never stored."),
    "gitlab_deploy_key_write_enabled": (HIGH, "Only fires when write_enabled_count > 0 on a gitlab_deploy_key_summary record — a direct count. Deploy key titles, fingerprints, and key material are never stored."),
    "gitlab_runner_untagged": (MEDIUM, "Fires when untagged_runner_count > 0 on a gitlab_runner_summary record; untagged runners may be intentional for some CI/CD configurations."),
    "gitlab_merge_request_approval_not_required": (MEDIUM, "Fires when approvals_required == 0 on a gitlab_merge_request_approval_summary record; some projects intentionally allow unreviewed merges."),
    # GitLab — M87C branch/webhook/CI risk expansion
    "gitlab_webhook_http_scheme": (HIGH, "Only fires when url_scheme is 'http' on an active gitlab_webhook record — a direct category derived from the webhook URL scheme in the connector. The raw URL is never stored."),
    "gitlab_webhook_broad_event_scope": (MEDIUM, "Fires when event_count >= 6 on an active gitlab_webhook record; some integrations legitimately subscribe to many event types."),
    "gitlab_webhook_pipeline_job_events": (MEDIUM, "Fires when pipeline_events or job_events is True on an active gitlab_webhook record; CI/CD event delivery is intentional for many webhook integrations."),
    "gitlab_branch_push_access_broad": (MEDIUM, "Fires when push_access_level_category is developer/reporter/guest on a protected/default/wildcard branch pattern; broad push access may be intentional for open development workflows."),
    "gitlab_branch_merge_access_broad": (MEDIUM, "Fires when merge_access_level_category is developer/reporter/guest on a protected/default/wildcard branch pattern; broad merge access may be intentional for teams using merge trains or specific workflows."),
    "gitlab_ci_variables_unprotected": (MEDIUM, "Fires when variable_count > 0 and protected_variable_count == 0 on a gitlab_ci_variable_summary record; some projects intentionally scope all variables to all branches. CI variable names and values are never stored."),
    "gitlab_ci_variables_unmasked": (MEDIUM, "Fires when variable_count > 0 and masked_variable_count == 0 on a gitlab_ci_variable_summary record; some variables that do not meet masking criteria (e.g. too short) may intentionally remain unmasked. CI variable names and values are never stored."),
    "gitlab_runner_shared_enabled": (MEDIUM, "Fires when shared_runner_enabled=True and runner_count > 0 on a gitlab_runner_summary record; shared runners are commonly used for open or public projects and may be intentional."),
    "gitlab_mr_approval_reset_disabled": (MEDIUM, "Fires when reset_approvals_on_push is explicitly False on a gitlab_merge_request_approval_summary record; some teams trust approvers to re-review manually after new pushes."),
    "gitlab_mr_approver_override_allowed": (MEDIUM, "Fires when disable_overriding_approvers_per_merge_request is explicitly False on a gitlab_merge_request_approval_summary record; some teams allow per-MR approval rule customization intentionally."),
    "gitlab_project_wiki_enabled_public": (MEDIUM, "Fires when wiki_enabled=True on a public gitlab_project record; public wikis are intentional for open-source projects that use them for documentation."),
    "gitlab_project_packages_enabled_public": (MEDIUM, "Fires when packages_enabled=True on a public gitlab_project record; public package registries are intentional for open-source distribution."),
    "gitlab_project_container_registry_enabled_public": (MEDIUM, "Fires when container_registry_enabled=True on a public gitlab_project record; public container registries may be intentional for public image distribution."),
    # ── M88B: Terraform Cloud core security rules ──────────────────────────────
    "terraform_cloud_organization_two_factor_not_required": (HIGH, "Only fires when two_factor_requirement_enabled is explicitly False on a terraform_cloud_organization record — a direct boolean from the API. Some organizations may rely on SSO as a compensating control."),
    "terraform_cloud_organization_sso_not_enabled": (HIGH, "Only fires when sso_enabled is explicitly False on a terraform_cloud_organization record. Many organizations use 2FA instead of SSO; review organizational auth policy before acting."),
    "terraform_cloud_workspace_auto_apply_enabled": (HIGH, "Only fires when auto_apply is True on a terraform_cloud_workspace record — a direct boolean. Some teams intentionally enable auto-apply for non-production workspaces."),
    "terraform_cloud_workspace_global_remote_state_enabled": (HIGH, "Only fires when global_remote_state is True on a terraform_cloud_workspace record — a direct boolean. Global state sharing may be intentional for shared infrastructure modules."),
    "terraform_cloud_workspace_local_execution_mode": (HIGH, "Only fires when execution_mode_category is 'local' on a terraform_cloud_workspace record. Local execution may be intentional for development or migration workspaces."),
    "terraform_cloud_workspace_vcs_connection_missing": (MEDIUM, "Fires when vcs_connected is False and execution_mode_category is 'remote' on a terraform_cloud_workspace record; some workspaces are intentionally API-driven without VCS."),
    "terraform_cloud_workspace_queue_all_runs_disabled": (MEDIUM, "Fires when queue_all_runs is False on a terraform_cloud_workspace record; some teams intentionally disable run queuing for certain workspace patterns."),
    "terraform_cloud_workspace_unpinned_terraform_version": (HIGH, "Only fires when terraform_version_category is 'latest' or 'unknown'. Using latest may be intentional in development environments."),
    "terraform_cloud_workspace_non_sensitive_variables_present": (MEDIUM, "Fires when non_sensitive_variable_count > 0 on a terraform_cloud_workspace_variable_summary record. Many workspaces intentionally use non-sensitive variables for non-secret configuration. Variable names and values are never stored."),
    "terraform_cloud_workspace_no_sensitive_variables": (MEDIUM, "Fires when sensitive_variable_count == 0 and variable_count > 0 on a terraform_cloud_workspace_variable_summary record. Some workspaces intentionally store only non-secret configuration variables. Variable names and values are never stored."),
    "terraform_cloud_notification_http_webhook": (HIGH, "Only fires when enabled=True, destination_type_category='webhook', and webhook_url_scheme_category='http'. Some internal webhook endpoints may be HTTP-only; webhook URLs are never stored."),
    "terraform_cloud_notification_token_missing": (MEDIUM, "Fires when enabled=True, destination_type_category='webhook', and token_present=False. Webhook token is optional if the receiver validates delivery through other means."),
    "terraform_cloud_policy_set_advisory_enforcement": (HIGH, "Only fires when enforcement_level_category='advisory'. Some policy sets are intentionally advisory for gradual rollout."),
    "terraform_cloud_policy_set_empty": (HIGH, "Only fires when policy_count==0. An empty policy set may be in setup and not yet populated."),
    "terraform_cloud_team_admin_access": (HIGH, "Only fires when admin_access_count > 0 on a terraform_cloud_team_access_summary record. Admin access may be required for platform teams. Team names are never stored."),
    "terraform_cloud_team_apply_access": (MEDIUM, "Fires when apply_access_count > 0 on a terraform_cloud_team_access_summary record. Apply access is commonly granted to deployment teams. Team names are never stored."),
    "terraform_cloud_variable_set_global_scope": (HIGH, "Only fires when global_scope is True on a terraform_cloud_variable_set record. Global scope is sometimes intentional for shared configuration. Variable names and values are never stored."),
    "terraform_cloud_state_version_present": (HIGH, "Only fires when state_version_present is True on a terraform_cloud_state_version_summary record. State presence is expected for active workspaces; this is an informational posture indicator. Raw state is never fetched or stored."),
    # ── M88C: Terraform Cloud workspace/variable/policy risk expansion ────────
    "terraform_cloud_workspace_agent_execution_mode": (HIGH, "Only fires when execution_mode_category=='agent' on a terraform_cloud_workspace record. Agent execution is an intentional choice; verify the agent pool meets your security requirements."),
    "terraform_cloud_workspace_file_triggers_disabled": (HIGH, "Only fires when file_triggers_enabled is False on a terraform_cloud_workspace record. File triggers may be intentionally disabled on workspaces driven by API calls rather than VCS pushes."),
    "terraform_cloud_workspace_speculative_plans_disabled": (HIGH, "Only fires when speculative_enabled is False on a terraform_cloud_workspace record. Speculative plans may be intentionally disabled on high-privilege or sensitive workspaces."),
    "terraform_cloud_workspace_run_triggers_present": (HIGH, "Only fires when run_trigger_count > 0 on a terraform_cloud_workspace record. Run triggers are a legitimate Terraform Cloud feature; count only, never source workspace identity."),
    "terraform_cloud_workspace_many_trigger_prefixes": (MEDIUM, "Fires when trigger_prefix_count >= 5 on a terraform_cloud_workspace record. A high prefix count is not inherently risky; the threshold is conservative."),
    "terraform_cloud_workspace_latest_run_failed": (HIGH, "Only fires when latest_run_status_category is in a review-worthy failure/error/canceled set. A single failed run may be transient; review in context."),
    "terraform_cloud_workspace_environment_variables_non_sensitive": (MEDIUM, "Fires when environment_variable_count > 0 and non_sensitive_variable_count > 0 on a terraform_cloud_workspace_variable_summary record. Non-sensitive env vars are common for configuration. Variable names and values are never stored."),
    "terraform_cloud_workspace_terraform_variables_non_sensitive": (MEDIUM, "Fires when terraform_variable_count > 0 and non_sensitive_variable_count > 0 on a terraform_cloud_workspace_variable_summary record. Non-sensitive Terraform vars are common for module inputs. Variable names and values are never stored."),
    "terraform_cloud_variable_set_non_sensitive_variables": (MEDIUM, "Fires when non_sensitive_variable_count > 0 on a terraform_cloud_variable_set record. Non-sensitive variables in a shared set may be intentional for configuration. Variable names and values are never stored."),
    "terraform_cloud_variable_set_broad_scope": (HIGH, "Only fires when global_scope is True and variable_count >= 5 on a terraform_cloud_variable_set record. Distinct from the M88B global scope rule; requires both global scope and a meaningful variable count."),
    "terraform_cloud_policy_set_global_scope": (HIGH, "Only fires when global_scope is True on a terraform_cloud_policy_set record. Global policy sets are sometimes intentional for organization-wide compliance."),
    "terraform_cloud_policy_set_broad_scope_advisory": (HIGH, "Fires when enforcement_level_category=='advisory' and the set is globally or broadly scoped. Advisory enforcement on broad scope provides no enforcement guarantee."),
    "terraform_cloud_policy_set_no_workspace_or_project_scope": (HIGH, "Fires when global_scope is False and workspace_count==0 and project_count==0. A scoped policy set with no targets is likely misconfigured or orphaned."),
    "terraform_cloud_notification_broad_trigger_scope": (MEDIUM, "Fires when enabled is True and trigger_count >= 5 on a terraform_cloud_notification_configuration record. High trigger counts may be intentional for comprehensive run alerting."),
    "terraform_cloud_notification_disabled": (HIGH, "Only fires when enabled is False on a terraform_cloud_notification_configuration record. A disabled notification may be intentionally decommissioned."),
    "terraform_cloud_run_trigger_enabled": (HIGH, "Fires on every emitted terraform_cloud_run_trigger record. Each record represents an active run trigger; review whether source workspace dependency is intentional."),
    "terraform_cloud_team_write_access": (MEDIUM, "Fires when write_access_count > 0 on a terraform_cloud_team_access_summary record. Write access is commonly granted to deployment teams. Team names are never stored."),
    "terraform_cloud_team_custom_permissions": (MEDIUM, "Fires when custom_permission_count > 0 on a terraform_cloud_team_access_summary record. Custom permissions are a legitimate Terraform Cloud feature for fine-grained access. Team names are never stored."),
}


def confidence_for(finding_key: str) -> tuple[str, str, str]:
    """Return (confidence, confidence_reason, false_positive_guard) for a finding.

    Looks up the base rule key. Unknown keys default to high confidence with a
    generic reason and no guard (preserves existing behavior — never suppresses).
    """
    rule_key = base_rule_key(finding_key)
    confidence, guard = RULE_CONFIDENCE.get(rule_key, (HIGH, ""))
    return confidence, _REASON.get(confidence, _REASON[HIGH]), guard


# Sanity: every known rule has a confidence entry, and none is low.
def _self_check() -> None:  # pragma: no cover - import-time guard
    missing = KNOWN_RULE_KEYS - set(RULE_CONFIDENCE)
    assert not missing, f"rules missing confidence: {sorted(missing)}"
    assert all(c in (HIGH, MEDIUM) for c, _ in RULE_CONFIDENCE.values())


_self_check()
