"""Security rule registry — M61.7.

Authoritative set of implemented security-rule keys (the prefix of a
``finding_key``, which is shaped ``rule_key:record_identifier``). Used by the
rule enable/disable settings to validate rule keys and by the evaluator to map a
finding back to its base rule.

Keep this in sync with the rule constants in ``app/services/security_rules/*``.
This is metadata only — it never evaluates provider state.
"""

from __future__ import annotations

# Exact rule keys emitted by app/services/security_rules/*.py (verified M61.7).
KNOWN_RULE_KEYS: frozenset[str] = frozenset(
    {
        # GitHub
        "github_webhook_http",
        "github_branch_protection_missing",
        "github_force_pushes_allowed",
        "github_branch_deletion_allowed",
        "github_pr_review_not_required",
        "github_status_checks_not_required",
        "github_deploy_key_write_access",
        "github_env_protection_missing",
        # GitHub rulesets (M69.5A)
        "github_ruleset_not_enforced",
        "github_ruleset_force_push_allowed",
        "github_ruleset_pr_review_missing",
        "github_ruleset_status_checks_missing",
        "github_ruleset_bypass_actors_present",
        "github_ruleset_weak_target_coverage",
        # GitHub automation permissions (M69.5B)
        "github_automation_admin_permission",
        "github_automation_write_permission",
        "github_token_broad_scopes",
        "github_webhook_secret_missing",
        # AWS
        "aws_public_admin_port",
        "aws_public_database_port",
        "aws_public_all_ports",
        "aws_s3_public_policy",
        "aws_s3_public_acl",
        "aws_iam_admin_policy_attached",
        "aws_access_key_unused",
        # Cloudflare
        "cloudflare_ssl_mode_weak",
        "cloudflare_always_https_off",
        "cloudflare_min_tls_weak",
        "cloudflare_security_level_low",
        "cloudflare_development_mode_on",
        "cloudflare_hsts_disabled",
        "cloudflare_waf_rule_disabled",
        "cloudflare_dns_private_origin",
        # Supabase
        "supabase_rls_disabled",
        "supabase_anonymous_access_enabled",
        "supabase_jwt_expiry_long",
        "supabase_public_select_sensitive_table",
        "supabase_public_write_policy",
        "supabase_edge_function_jwt_disabled",
        "supabase_auth_protection_missing",
        # Firebase
        "firebase_rules_public",
        "firebase_storage_rules_public",
        "firebase_anonymous_auth_enabled",
        # Firebase — M72A (Realtime Database rules + auth hardening)
        "firebase_database_public_read",
        "firebase_database_public_write",
        "firebase_auth_protection_missing",
        # Stripe
        "stripe_webhook_http",
        # Stripe — M73A (webhook posture + payment links + portal + account)
        "stripe_webhook_disabled",
        "stripe_webhook_broad_events",
        "stripe_payment_link_tax_disabled",
        "stripe_payment_link_promo_codes_enabled",
        "stripe_portal_subscription_cancel_enabled",
        "stripe_portal_login_enabled",
        "stripe_account_capability_incomplete",
        # Vercel
        "vercel_preview_unprotected",
        "vercel_production_branch_missing",
        "vercel_production_branch_unusual",
        "vercel_domain_unverified",
        "vercel_env_var_broad_target",
        "vercel_sensitive_env_var_broad_scope",
        "vercel_deploy_hook_production_branch",
        # Shopify
        "shopify_webhook_http",
        # Shopify — M74A
        "shopify_webhook_high_risk_topic",
        "shopify_app_broad_write_scopes",
        "shopify_app_customer_data_scope",
        "shopify_domain_ssl_missing",
        "shopify_domain_unverified",
        "shopify_policy_missing",
        # Azure — M77B
        "azure_nsg_public_admin_ingress",
        "azure_nsg_public_broad_ingress",
        "azure_storage_public_blob_access",
        "azure_storage_public_network_access",
        "azure_storage_weak_tls",
        "azure_storage_shared_key_enabled",
        "azure_key_vault_public_network_access",
        "azure_key_vault_purge_protection_disabled",
        "azure_key_vault_soft_delete_disabled",
        "azure_key_vault_rbac_disabled",
        # Azure — M77C
        "azure_role_assignment_broad_privilege",
        "azure_app_service_https_disabled",
        "azure_app_service_ftp_enabled",
        "azure_app_service_weak_tls",
        "azure_app_service_public_network_access",
        "azure_sql_public_network_access",
        "azure_sql_weak_tls",
        "azure_aks_local_accounts_enabled",
        "azure_aks_public_api_access",
        "azure_aks_network_policy_missing",
        # Google Cloud — M78B
        "google_cloud_iam_public_member",
        "google_cloud_iam_broad_privileged_role",
        "google_cloud_firewall_public_admin_ingress",
        "google_cloud_firewall_public_broad_ingress",
        "google_cloud_firewall_rule_no_targets",
        "google_cloud_storage_public_access_prevention_disabled",
        "google_cloud_storage_uniform_access_disabled",
        "google_cloud_storage_versioning_disabled",
        "google_cloud_storage_retention_not_locked",
        # Google Cloud — M78C
        "google_cloud_sql_public_network_access",
        "google_cloud_sql_weak_tls",
        "google_cloud_sql_backups_disabled",
        "google_cloud_sql_deletion_protection_disabled",
        "google_cloud_run_public_invoker",
        "google_cloud_run_all_ingress",
        "google_cloud_gke_public_control_plane",
        "google_cloud_gke_legacy_abac_enabled",
        "google_cloud_gke_network_policy_disabled",
        "google_cloud_gke_workload_identity_disabled",
        "google_cloud_service_account_user_managed_keys",
        "google_cloud_service_account_old_keys",
        "google_cloud_secret_manager_auto_replication_without_cmek",
        # Twilio — M79B
        "twilio_phone_number_sms_webhook_missing",
        "twilio_phone_number_voice_webhook_missing",
        "twilio_phone_number_status_callback_missing",
        "twilio_messaging_service_inbound_webhook_missing",
        "twilio_messaging_service_fallback_missing",
        "twilio_messaging_service_status_callback_missing",
        "twilio_verify_short_code_length",
        "twilio_verify_lookup_disabled",
        "twilio_account_suspended",
        # Twilio — M79C
        "twilio_api_key_stale",
        "twilio_messaging_service_observability_gap",
        "twilio_messaging_service_number_level_inbound_webhook",
        "twilio_messaging_service_long_validity_period",
        "twilio_phone_number_messaging_observability_gap",
        "twilio_phone_number_voice_observability_gap",
        "twilio_verify_psd2_disabled",
        "twilio_verify_sms_to_landlines_allowed",
        # SendGrid — M80B
        "sendgrid_api_key_broad_scopes",
        "sendgrid_sender_identity_unverified",
        "sendgrid_sender_identity_locked",
        "sendgrid_domain_authentication_invalid",
        "sendgrid_domain_automatic_security_disabled",
        "sendgrid_domain_authentication_legacy",
        "sendgrid_spam_check_disabled",
        "sendgrid_sandbox_mode_enabled",
        "sendgrid_bcc_enabled",
        "sendgrid_click_tracking_enabled",
        "sendgrid_open_tracking_enabled",
        "sendgrid_subscription_tracking_disabled",
        "sendgrid_event_webhook_disabled",
        "sendgrid_event_webhook_url_missing",
        "sendgrid_suppression_settings_empty",
        # SendGrid — M80C
        "sendgrid_sender_identity_reply_domain_mismatch",
        "sendgrid_domain_dns_records_missing",
        "sendgrid_default_domain_authentication_invalid",
        "sendgrid_footer_disabled",
        "sendgrid_bounce_purge_disabled",
        "sendgrid_template_engine_enabled",
        "sendgrid_google_analytics_tracking_enabled",
        "sendgrid_event_webhook_broad_event_stream",
        "sendgrid_inbound_parse_enabled",
        "sendgrid_inbound_parse_raw_email_enabled",
        "sendgrid_inbound_parse_spam_check_disabled",
        # Auth0 — M81B
        "auth0_tenant_session_lifetime_extended",
        "auth0_tenant_idle_session_lifetime_extended",
        "auth0_tenant_dynamic_client_registration_enabled",
        "auth0_application_no_callbacks",
        "auth0_application_many_callbacks",
        "auth0_application_many_allowed_origins",
        "auth0_application_oidc_non_conformant",
        "auth0_application_weak_jwt_algorithm",
        "auth0_refresh_token_rotation_disabled",
        "auth0_refresh_token_lifetime_extended",
        "auth0_connection_no_enabled_clients",
        "auth0_connection_weak_password_policy",
        "auth0_resource_server_offline_access_enabled",
        "auth0_resource_server_token_lifetime_extended",
        "auth0_resource_server_rbac_disabled",
        "auth0_rule_disabled",
        "auth0_rule_large_script",
        "auth0_action_not_deployed",
        "auth0_action_secrets_present",
        "auth0_mfa_factor_disabled",
        "auth0_custom_domain_not_ready",
        "auth0_custom_domain_weak_tls_policy",
        # Auth0 — M81C OAuth/application risk expansion
        "auth0_application_password_grant_enabled",
        "auth0_application_implicit_grant_enabled",
        "auth0_application_public_client_credentials_enabled",
        "auth0_application_refresh_grant_without_rotation",
        "auth0_application_many_grant_types",
        "auth0_application_device_code_grant_enabled",
        "auth0_application_wildcard_callback",
        "auth0_application_wildcard_allowed_origin",
        "auth0_application_wildcard_logout_url",
        "auth0_application_localhost_callback",
        "auth0_application_localhost_origin",
        "auth0_application_callback_missing_https",
        "auth0_application_origin_missing_https",
        "auth0_public_client_refresh_tokens_enabled",
        "auth0_application_token_endpoint_auth_none",
        # Datadog — M82B core security rules
        "datadog_monitor_disabled",
        "datadog_monitor_unrestricted_roles",
        "datadog_monitor_notify_no_data_disabled",
        "datadog_monitor_long_query",
        "datadog_slo_no_monitors",
        "datadog_slo_low_target",
        "datadog_dashboard_public_url_present",
        "datadog_dashboard_unrestricted_roles",
        "datadog_webhook_without_secret_headers",
        "datadog_webhook_payload_template_present",
        "datadog_notification_integration_no_channels",
        "datadog_application_key_broad_scopes",
        "datadog_api_key_disabled",
        "datadog_role_high_permission_count",
        "datadog_team_no_members",
        "datadog_cloud_integration_broad_collection",
        "datadog_cloud_integration_log_collection_enabled",
        # Datadog — M82C monitor/webhook risk expansion
        "datadog_monitor_no_notifications",
        "datadog_monitor_message_template_present",
        "datadog_monitor_no_warning_threshold",
        "datadog_monitor_no_recovery_threshold",
        "datadog_monitor_silenced_scopes_present",
        "datadog_monitor_notify_audit_disabled",
        "datadog_monitor_require_full_window_disabled",
        "datadog_monitor_query_wildcard_scope",
        "datadog_monitor_broad_group_by",
        "datadog_monitor_long_no_data_timeframe",
        "datadog_webhook_custom_headers_without_secret_headers",
        "datadog_webhook_large_payload_template",
        "datadog_webhook_auth_material_present",
        "datadog_webhook_non_https_endpoint",
        # Clerk — M83B core security rules
        "clerk_instance_mfa_disabled",
        "clerk_instance_password_without_mfa",
        "clerk_instance_sign_up_enabled",
        "clerk_application_mfa_not_required",
        "clerk_domain_unverified",
        "clerk_domain_ssl_disabled",
        "clerk_redirect_url_non_https",
        "clerk_redirect_url_wildcard_present",
        "clerk_redirect_url_localhost_present",
        "clerk_jwt_template_custom_claims_present",
        "clerk_jwt_template_long_lifetime",
        "clerk_webhook_endpoint_disabled",
        "clerk_webhook_without_signing",
        "clerk_webhook_non_https",
        "clerk_email_sms_custom_sender_present",
        "clerk_auth_strategy_mfa_not_required",
        "clerk_auth_strategy_password_without_mfa",
        "clerk_session_lifetime_extended",
        "clerk_session_inactivity_timeout_extended",
        "clerk_session_single_session_disabled",
        "clerk_session_token_rotation_disabled",
        # Clerk — M83C auth/application risk expansion
        "clerk_application_sign_up_enabled",
        "clerk_application_password_without_mfa",
        "clerk_application_oauth_without_mfa",
        "clerk_application_saml_without_mfa",
        "clerk_application_many_redirect_urls",
        "clerk_application_many_allowed_origins",
        "clerk_redirect_url_custom_scheme_present",
        "clerk_jwt_template_audience_missing",
        "clerk_jwt_template_issuer_missing",
        "clerk_jwt_template_many_claims",
        "clerk_webhook_broad_event_scope",
        "clerk_org_verified_domains_not_required",
        "clerk_org_invitations_enabled",
        "clerk_org_admin_role_missing",
        "clerk_org_high_role_count",
        "clerk_org_high_permission_count",
        "clerk_session_device_tracking_disabled",
        "clerk_session_reverification_disabled",
        "clerk_session_long_lifetime_without_single_session",
        # PagerDuty — M84B core security rules
        "pagerduty_service_no_escalation_policy",
        "pagerduty_service_no_integrations",
        "pagerduty_service_ack_timeout_disabled",
        "pagerduty_service_auto_resolve_disabled",
        "pagerduty_service_alert_creation_limited",
        "pagerduty_service_no_teams",
        "pagerduty_escalation_policy_no_rules",
        "pagerduty_escalation_policy_single_level",
        "pagerduty_schedule_no_layers",
        "pagerduty_schedule_no_teams",
        "pagerduty_service_integration_missing_key_indicator",
        "pagerduty_service_integration_email_type",
        "pagerduty_webhook_subscription_inactive",
        "pagerduty_webhook_subscription_non_https",
        "pagerduty_webhook_subscription_broad_event_scope",
        "pagerduty_event_orchestration_no_routes",
        "pagerduty_event_orchestration_no_team",
        "pagerduty_business_service_no_team",
        "pagerduty_business_service_no_contact",
        "pagerduty_response_play_no_responders",
        "pagerduty_response_play_no_subscribers",
        "pagerduty_response_play_not_runnable",
        # PagerDuty — M84C escalation/webhook risk expansion
        "pagerduty_escalation_policy_no_targets",
        "pagerduty_escalation_policy_low_target_count",
        "pagerduty_escalation_policy_no_schedule_targets",
        "pagerduty_escalation_policy_no_team_targets",
        "pagerduty_schedule_no_targets",
        "pagerduty_schedule_low_target_count",
        "pagerduty_schedule_single_layer",
        "pagerduty_schedule_no_restrictions",
        "pagerduty_service_integration_routing_key_missing",
        "pagerduty_service_integration_unknown_type",
        "pagerduty_webhook_subscription_no_events",
        "pagerduty_webhook_subscription_secret_not_indicated",
        "pagerduty_webhook_subscription_broad_scope_high",
        "pagerduty_webhook_subscription_account_scope",
        "pagerduty_event_orchestration_low_route_count",
        "pagerduty_response_play_low_responder_count",
        "pagerduty_response_play_no_team",
        "pagerduty_response_play_manual_only",
        # Linear — M85B core security rules
        "linear_workspace_missing_url_key",
        "linear_workspace_missing_logo",
        "linear_team_private",
        "linear_team_low_member_count",
        "linear_team_no_projects",
        "linear_team_auto_archive_disabled",
        "linear_team_cycles_disabled",
        "linear_team_long_cycle_duration",
        "linear_project_no_lead",
        "linear_project_no_members",
        "linear_project_high_issue_count",
        "linear_project_unhealthy",
        "linear_project_unknown_status",
        "linear_workflow_state_unknown_type",
        "linear_label_missing_team_scope",
        "linear_webhook_disabled",
        "linear_webhook_no_secret_indicator",
        "linear_webhook_non_https",
        "linear_webhook_no_events",
        "linear_webhook_broad_resource_scope",
        "linear_view_shared",
        "linear_cycle_high_issue_count",
        "linear_integration_disabled",
        "linear_integration_unknown_type",
        # Linear — M85C workflow/webhook risk expansion
        "linear_workspace_low_team_count",
        "linear_workspace_no_webhooks",
        "linear_workspace_no_integrations",
        "linear_team_no_backlog_state",
        "linear_team_no_started_state",
        "linear_team_no_completed_state",
        "linear_team_no_canceled_state",
        "linear_team_low_workflow_state_count",
        "linear_team_no_labels",
        "linear_team_no_webhooks",
        "linear_project_no_team_scope",
        "linear_webhook_issue_comment_scope",
        "linear_webhook_attachment_scope",
        "linear_view_shared_without_team_scope",
        "linear_integration_workspace_scoped",
        # Jira core security rules — M86B
        "jira_site_missing_url",
        "jira_site_no_projects",
        "jira_site_no_webhooks",
        "jira_site_no_automation_rules",
        "jira_project_missing_key",
        "jira_project_private",
        "jira_project_archived",
        "jira_project_deleted",
        "jira_project_simplified",
        "jira_project_unknown_type_category",
        "jira_project_unknown_style_category",
        "jira_project_no_boards",
        "jira_project_no_issue_types",
        "jira_project_no_lead",
        "jira_board_missing_project_link",
        "jira_board_unknown_type_category",
        "jira_board_unknown_location_type",
        "jira_workflow_inactive",
        "jira_workflow_no_statuses",
        "jira_workflow_no_transitions",
        "jira_workflow_excessive_global_transitions",
        "jira_workflow_scheme_unused",
        "jira_workflow_scheme_no_default",
        "jira_permission_scheme_anonymous_grant",
        "jira_permission_scheme_anyone_grant",
        "jira_permission_scheme_logged_in_grant",
        "jira_notification_scheme_email_recipients",
        "jira_notification_scheme_group_recipients",
        "jira_notification_scheme_no_notifications",
        "jira_issue_type_scheme_no_default",
        "jira_issue_type_scheme_no_types",
        "jira_field_configuration_scheme_no_configurations",
        "jira_field_configuration_scheme_hidden_required_conflict",
        "jira_screen_scheme_no_fields",
        "jira_screen_scheme_no_screens",
        "jira_webhook_disabled",
        "jira_webhook_no_secret_indicator",
        "jira_webhook_non_https",
        "jira_webhook_no_events",
        "jira_webhook_no_jql_filter",
        "jira_automation_rule_disabled",
        "jira_automation_rule_unknown_trigger",
        "jira_automation_rule_global_scope",
        # Jira workflow/webhook risk expansion — M86C
        "jira_workflow_no_done_status",
        "jira_workflow_no_in_progress_status",
        "jira_workflow_high_transition_rule_count",
        "jira_workflow_high_validator_count",
        "jira_workflow_high_condition_count",
        "jira_workflow_high_post_function_count",
        "jira_workflow_orphan_statuses",
        "jira_workflow_scheme_unmapped_issue_types",
        "jira_workflow_scheme_low_workflow_count",
        "jira_workflow_scheme_high_issue_type_mapping_count",
        "jira_permission_scheme_public_browse_projects",
        "jira_permission_scheme_public_administer_projects",
        "jira_permission_scheme_public_manage_sprints",
        "jira_permission_scheme_public_create_issues",
        "jira_permission_scheme_public_transition_issues",
        "jira_permission_scheme_unknown_holder",
        "jira_permission_scheme_high_privilege_grants",
        "jira_permission_scheme_high_public_grant_count",
        "jira_notification_scheme_unknown_recipients",
        "jira_notification_scheme_high_event_count",
        "jira_webhook_comment_event_scope",
        "jira_webhook_attachment_event_scope",
        "jira_webhook_sprint_event_scope",
        "jira_webhook_worklog_event_scope",
        "jira_webhook_all_issue_events",
        "jira_automation_rule_web_request_action",
        "jira_automation_rule_email_action",
        "jira_automation_rule_external_action",
        "jira_automation_rule_comment_action",
        "jira_automation_rule_high_action_count",
        "jira_automation_rule_high_branch_count",
        "jira_automation_rule_multi_project_scope",
        "jira_automation_rule_unknown_scope",
        "jira_board_no_filter_indicator",
        "jira_board_broad_jql_filter",
        "jira_board_high_quick_filter_count",
        "jira_board_unknown_swimlane_strategy",
        "jira_board_no_columns",
        "jira_screen_scheme_unmapped_screens",
        # GitLab — M87B core security rules
        "gitlab_project_public_visibility",
        "gitlab_project_shared_runners_enabled",
        "gitlab_project_snippets_enabled_public",
        "gitlab_group_public_visibility",
        "gitlab_branch_force_push_enabled",
        "gitlab_branch_code_owner_approval_missing",
        "gitlab_webhook_secret_missing",
        "gitlab_webhook_ssl_verification_disabled",
        "gitlab_ci_unprotected_unmasked_variables",
        "gitlab_deploy_key_write_enabled",
        "gitlab_runner_untagged",
        "gitlab_merge_request_approval_not_required",
        # GitLab — M87C branch/webhook/CI risk expansion
        "gitlab_webhook_http_scheme",
        "gitlab_webhook_broad_event_scope",
        "gitlab_webhook_pipeline_job_events",
        "gitlab_branch_push_access_broad",
        "gitlab_branch_merge_access_broad",
        "gitlab_ci_variables_unprotected",
        "gitlab_ci_variables_unmasked",
        "gitlab_runner_shared_enabled",
        "gitlab_mr_approval_reset_disabled",
        "gitlab_mr_approver_override_allowed",
        "gitlab_project_wiki_enabled_public",
        "gitlab_project_packages_enabled_public",
        "gitlab_project_container_registry_enabled_public",
    }
)


def is_known_rule_key(rule_key: str) -> bool:
    """True when *rule_key* is an implemented security rule."""
    return rule_key in KNOWN_RULE_KEYS


def base_rule_key(finding_key: str) -> str:
    """Return the rule key portion of a ``finding_key`` (``rule_key:record_id``).

    If there is no colon, the whole string is treated as the rule key.
    """
    if not finding_key:
        return finding_key
    idx = finding_key.find(":")
    return finding_key if idx < 0 else finding_key[:idx]
