/**
 * securityRuleCatalog.ts — read-only catalog of the Configuration Risk rules
 * ConfigTrace evaluates (M60.9).
 *
 * This is a STATIC mirror of the backend rules implemented in
 * backend/app/services/security_rules/*.py (M60.4–M60.4.5). Every entry's
 * `key` matches a real backend rule_key. It is intentionally a hand-maintained
 * catalog (no backend endpoint exists for rule metadata yet); when a backend
 * rule is added/changed, update this file to match.
 *
 * Nothing here claims breach/threat detection. All rules evaluate provider
 * CONFIGURATION snapshots for risky current states, using metadata only.
 */

export type RuleSeverity = "critical" | "high" | "medium" | "low" | "info";
export type RuleConfidence = "high" | "medium";

export interface SecurityRuleMeta {
  key: string;
  provider: string; // matches getProviderMeta ids: github/aws/cloudflare/…
  severity: RuleSeverity; // headline (worst case the rule can emit)
  severityNote?: string;
  title: string;
  category: string;
  confidence: RuleConfidence;
  metadataOnly: true;
  description: string;
  whatItChecks: string;
  whyItMatters: string;
  evidence: string;
  remediation: string;
  falsePositiveGuard: string;
}

export interface DeferredRuleMeta {
  provider: string;
  title: string;
  reason: string;
}

export interface ProviderCoverage {
  provider: string;
  surfaces: string[];
}

// ── Implemented rules (exact keys from backend security_rules/*) ─────────────

export const SECURITY_RULES: SecurityRuleMeta[] = [
  // ── GitHub ────────────────────────────────────────────────────────────────
  {
    key: "github_webhook_http",
    provider: "github",
    severity: "critical",
    title: "GitHub webhook uses plain HTTP",
    category: "Webhooks",
    confidence: "high",
    metadataOnly: true,
    description: "An active GitHub webhook delivers events over plain HTTP.",
    whatItChecks: "Each active webhook's delivery URL scheme.",
    whyItMatters:
      "Event payloads and signature headers may be transmitted in cleartext, which could allow interception or tampering.",
    evidence: "Webhook delivery URL (scheme/host/path).",
    remediation: "Restore HTTPS on the endpoint and verify ownership.",
    falsePositiveGuard: "Only fires for active webhooks whose URL begins with http://.",
  },
  {
    key: "github_branch_protection_missing",
    provider: "github",
    severity: "high",
    title: "GitHub default branch has no protection",
    category: "Branch protection",
    confidence: "high",
    metadataOnly: true,
    description: "The default branch has no branch protection rule.",
    whatItChecks: "Whether protection is enabled on the repository's default branch.",
    whyItMatters:
      "Commits can be pushed directly without review, and history can be rewritten or the branch deleted.",
    evidence: "Branch name and protection-enabled flag.",
    remediation: "Enable branch protection: require reviews, status checks, and block force pushes/deletions.",
    falsePositiveGuard:
      "Only the default branch is evaluated; a 403/permission error aborts the fetch before this fires, so a 404→disabled reliably means 'no rule configured'.",
  },
  {
    key: "github_force_pushes_allowed",
    provider: "github",
    severity: "high",
    title: "GitHub default branch allows force pushes",
    category: "Branch protection",
    confidence: "high",
    metadataOnly: true,
    description: "Force pushes are permitted on the protected default branch.",
    whatItChecks: "The allow_force_pushes flag on an enabled protection rule.",
    whyItMatters: "History can be rewritten, erasing the audit trail.",
    evidence: "Branch name and force-pushes-allowed flag.",
    remediation: "Disable 'Allow force pushes' in branch protection.",
    falsePositiveGuard: "Only evaluated when protection is enabled (sub-rules are skipped when protection is missing).",
  },
  {
    key: "github_branch_deletion_allowed",
    provider: "github",
    severity: "high",
    title: "GitHub default branch allows deletion",
    category: "Branch protection",
    confidence: "high",
    metadataOnly: true,
    description: "Branch deletion is permitted on the protected default branch.",
    whatItChecks: "The allow_deletions flag on an enabled protection rule.",
    whyItMatters: "The protected branch could be removed.",
    evidence: "Branch name and deletions-allowed flag.",
    remediation: "Disable 'Allow deletions' in branch protection.",
    falsePositiveGuard: "Only evaluated when protection is enabled.",
  },
  {
    key: "github_pr_review_not_required",
    provider: "github",
    severity: "high",
    title: "GitHub default branch does not require PR review",
    category: "Branch protection",
    confidence: "high",
    metadataOnly: true,
    description: "The protected default branch does not require an approving review before merge.",
    whatItChecks: "Whether PR reviews are required and the approving-review count is ≥ 1.",
    whyItMatters: "Unreviewed code can reach production.",
    evidence: "Branch name and required-review count.",
    remediation: "Require at least one approving review; enable dismiss-stale-approvals.",
    falsePositiveGuard: "Only evaluated when protection is enabled.",
  },
  {
    key: "github_status_checks_not_required",
    provider: "github",
    severity: "medium",
    title: "GitHub default branch does not require status checks",
    category: "Branch protection",
    confidence: "high",
    metadataOnly: true,
    description: "The protected default branch does not require status checks before merge.",
    whatItChecks: "The required_status_checks_enabled flag on an enabled protection rule.",
    whyItMatters: "Broken or failing code can be merged.",
    evidence: "Branch name and status-checks-required flag.",
    remediation: "Require status checks to pass before merging.",
    falsePositiveGuard: "Only evaluated when protection is enabled.",
  },
  {
    key: "github_deploy_key_write_access",
    provider: "github",
    severity: "high",
    title: "GitHub deploy key has write access",
    category: "Deploy keys",
    confidence: "high",
    metadataOnly: true,
    description: "A repository deploy key has read-write access.",
    whatItChecks: "The read_only flag on each deploy key.",
    whyItMatters: "A leaked write-capable deploy key allows pushing malicious code.",
    evidence: "Deploy key title, id, and verified flag (never key material).",
    remediation: "Recreate the key as read-only or remove it if unused.",
    falsePositiveGuard: "Missing read_only defaults to read-only (safe), so partial records are ignored.",
  },
  {
    key: "github_env_protection_missing",
    provider: "github",
    severity: "medium",
    title: "GitHub production environment has no protection rules",
    category: "Environment protection",
    confidence: "high",
    metadataOnly: true,
    description: "A production environment has no reviewers, wait timer, or branch policy.",
    whatItChecks: "Environments named production/prod with zero reviewers, zero wait timer, and no branch policy.",
    whyItMatters: "Anyone able to run a workflow can deploy to production without approval.",
    evidence: "Environment name, required reviewers, wait timer, branch-policy flag.",
    remediation: "Add required reviewers and restrict deployments to protected branches.",
    falsePositiveGuard: "Narrowly scoped to environments explicitly named production/prod.",
  },

  // ── GitHub rulesets (M69.5A) ────────────────────────────────────────────────
  {
    key: "github_ruleset_not_enforced",
    provider: "github",
    severity: "high",
    title: "GitHub ruleset is not actively enforced",
    category: "Rulesets",
    confidence: "high",
    metadataOnly: true,
    description: "A ruleset is set to disabled/evaluate rather than actively enforced.",
    whatItChecks: "The ruleset enforcement field; flags anything other than 'active'.",
    whyItMatters: "Repository protection the ruleset defines may not apply, which may weaken protection.",
    evidence: "Ruleset name, enforcement, target, protected-branch flag.",
    remediation: "Set the ruleset enforcement status to 'Active'.",
    falsePositiveGuard: "Reads the enforcement field directly; only fires when it is not 'active'.",
  },
  {
    key: "github_ruleset_force_push_allowed",
    provider: "github",
    severity: "high",
    title: "GitHub ruleset allows force pushes",
    category: "Rulesets",
    confidence: "high",
    metadataOnly: true,
    description: "An active branch ruleset does not block force pushes.",
    whatItChecks: "Whether an active branch ruleset includes a non-fast-forward (block force push) rule.",
    whyItMatters: "History can be rewritten, erasing the audit trail.",
    evidence: "Ruleset name, force-pushes-allowed flag, target.",
    remediation: "Add a 'Block force pushes' (non-fast-forward) rule to the ruleset.",
    falsePositiveGuard: "Only fires for active branch rulesets that lack the non-fast-forward rule.",
  },
  {
    key: "github_ruleset_pr_review_missing",
    provider: "github",
    severity: "high",
    title: "GitHub ruleset does not require pull request review",
    category: "Rulesets",
    confidence: "medium",
    metadataOnly: true,
    description: "An active ruleset targets a protected branch but does not require PR review.",
    whatItChecks: "Whether an active protected-branch ruleset includes a pull_request rule.",
    whyItMatters: "Unreviewed code can reach protected branches.",
    evidence: "Ruleset name, PR-review-required flag, protected-branch flag.",
    remediation: "Add a 'Require a pull request before merging' rule to the ruleset.",
    falsePositiveGuard: "Depends on the protected-branch target heuristic; only active branch rulesets are evaluated.",
  },
  {
    key: "github_ruleset_status_checks_missing",
    provider: "github",
    severity: "medium",
    title: "GitHub ruleset does not require status checks",
    category: "Rulesets",
    confidence: "medium",
    metadataOnly: true,
    description: "An active ruleset targets a protected branch but requires no status checks.",
    whatItChecks: "The required-status-checks count on an active protected-branch ruleset.",
    whyItMatters: "Broken or failing code can be merged.",
    evidence: "Ruleset name, required-status-checks count, protected-branch flag.",
    remediation: "Add a 'Require status checks to pass' rule to the ruleset.",
    falsePositiveGuard: "Depends on the protected-branch target heuristic; only active branch rulesets are evaluated.",
  },
  {
    key: "github_ruleset_bypass_actors_present",
    provider: "github",
    severity: "medium",
    title: "GitHub ruleset has bypass actors",
    category: "Rulesets",
    confidence: "high",
    metadataOnly: true,
    description: "An active ruleset grants one or more actors the ability to skip its rules.",
    whatItChecks: "The bypass-actor count on an active ruleset (counts only, never identities).",
    whyItMatters: "Bypass grants may weaken the protection the ruleset is meant to enforce.",
    evidence: "Ruleset name and bypass-actor count.",
    remediation: "Review the ruleset's bypass list and remove unnecessary actors.",
    falsePositiveGuard: "Reads the bypass-actor count directly; counts only, never identities.",
  },
  {
    key: "github_ruleset_weak_target_coverage",
    provider: "github",
    severity: "medium",
    title: "GitHub ruleset does not cover the default branch",
    category: "Rulesets",
    confidence: "medium",
    metadataOnly: true,
    description: "An active branch ruleset does not appear to target the default/main branch.",
    whatItChecks: "A default-branch coverage heuristic over the ruleset's branch targets.",
    whyItMatters: "Protection may not apply where it matters most.",
    evidence: "Ruleset name, protected-branch flag, target.",
    remediation: "Extend the ruleset's target patterns to cover the default branch.",
    falsePositiveGuard: "Based on a default-branch coverage heuristic; conservative and may under-report.",
  },

  // ── GitHub automation permissions (M69.5B) ──────────────────────────────────
  {
    key: "github_automation_admin_permission",
    provider: "github",
    severity: "high",
    title: "GitHub automation credential has admin repository permission",
    category: "Automation permissions",
    confidence: "high",
    metadataOnly: true,
    description: "The authenticated automation credential has admin permission on this repository.",
    whatItChecks: "The repository permission object GitHub returns for the authenticated credential.",
    whyItMatters: "Admin access broadens the blast radius of the credential beyond what monitoring usually requires.",
    evidence: "Credential type, admin-permission flag, broad-permission count.",
    remediation: "Reduce the automation credential to the least privilege it needs (prefer read-only).",
    falsePositiveGuard: "Reads the credential's repository permission object directly; no value is fabricated.",
  },
  {
    key: "github_automation_write_permission",
    provider: "github",
    severity: "medium",
    title: "GitHub automation credential has write permission",
    category: "Automation permissions",
    confidence: "high",
    metadataOnly: true,
    description: "The authenticated automation credential has write/push permission where read-only would usually be safer.",
    whatItChecks: "The push/maintain flags on the credential's repository permission object.",
    whyItMatters: "Write access may increase the blast radius of the credential.",
    evidence: "Credential type, push/maintain flags, broad-permission count.",
    remediation: "Reduce the automation credential to read-only where possible.",
    falsePositiveGuard: "Only fires when admin is not already set; reads the permission object directly.",
  },
  {
    key: "github_token_broad_scopes",
    provider: "github",
    severity: "high",
    title: "GitHub token appears broadly scoped",
    category: "Automation permissions",
    confidence: "medium",
    metadataOnly: true,
    description: "The automation token carries broad repository/admin OAuth scopes.",
    whatItChecks: "Classic-PAT OAuth scope names from the X-OAuth-Scopes response header.",
    whyItMatters: "A broadly scoped token increases the blast radius of the credential.",
    evidence: "Credential type, broad scope names, scope count.",
    remediation: "Replace the broadly scoped token with a least-privilege fine-grained token or GitHub App.",
    falsePositiveGuard: "Classic-PAT scopes only; fine-grained tokens/Apps expose no scopes, so it may under-report.",
  },
  {
    key: "github_webhook_secret_missing",
    provider: "github",
    severity: "medium",
    title: "GitHub webhook has no secret configured",
    category: "Webhooks",
    confidence: "high",
    metadataOnly: true,
    description: "A GitHub webhook has no signing secret configured.",
    whatItChecks: "Whether the webhook config includes a secret (presence boolean only — never the value).",
    whyItMatters: "Without a secret, delivered payloads cannot be verified, so the endpoint may be easier to spoof.",
    evidence: "Webhook secret-configured boolean.",
    remediation: "Configure a webhook secret and verify signatures on delivery.",
    falsePositiveGuard: "GitHub reliably masks a configured secret and omits the field when none is set.",
  },

  // ── AWS ───────────────────────────────────────────────────────────────────
  {
    key: "aws_public_admin_port",
    provider: "aws",
    severity: "high",
    title: "AWS security group exposes administrative ports to the internet",
    category: "Security groups",
    confidence: "high",
    metadataOnly: true,
    description: "An inbound rule allows public access to admin ports (SSH/RDP/WinRM).",
    whatItChecks: "Ingress rules where is_public is true and port_category is admin.",
    whyItMatters:
      "If the group is attached to an internet-reachable resource, admin ports are reachable from anywhere.",
    evidence: "Security group id, direction, protocol, ports, CIDR, port category.",
    remediation: "Restrict to trusted CIDRs; prefer a bastion/VPN.",
    falsePositiveGuard:
      "Only 0.0.0.0/0 or ::/0 count as public; language is careful since reachability is not proven from the rule alone.",
  },
  {
    key: "aws_public_database_port",
    provider: "aws",
    severity: "critical",
    title: "AWS security group exposes database ports to the internet",
    category: "Security groups",
    confidence: "high",
    metadataOnly: true,
    description: "An inbound rule allows public access to database ports.",
    whatItChecks: "Ingress rules where is_public is true and port_category is database.",
    whyItMatters: "Databases reachable from the public internet are a high-impact exposure.",
    evidence: "Security group id, ports, CIDR, port category.",
    remediation: "Restrict to trusted CIDRs or private networking only.",
    falsePositiveGuard: "Only canonical 'any' CIDRs count as public.",
  },
  {
    key: "aws_public_all_ports",
    provider: "aws",
    severity: "critical",
    title: "AWS security group exposes all ports to the internet",
    category: "Security groups",
    confidence: "high",
    metadataOnly: true,
    description: "An all-traffic inbound rule is open to the public internet.",
    whatItChecks: "Ingress rules where is_public is true and the protocol is all-traffic.",
    whyItMatters: "Every port is reachable from anywhere if attached to a public resource.",
    evidence: "Security group id, protocol, CIDR.",
    remediation: "Replace the all-traffic rule with least-privilege rules.",
    falsePositiveGuard: "Only canonical 'any' CIDRs count as public.",
  },
  {
    key: "aws_s3_public_policy",
    provider: "aws",
    severity: "critical",
    title: "AWS S3 bucket policy allows public access",
    category: "S3 public access",
    confidence: "high",
    metadataOnly: true,
    description: "A bucket policy grants public access (AWS's own determination).",
    whatItChecks: "policy_status_is_public / public_principals_detected on the bucket.",
    whyItMatters: "Objects may be readable or writable by anyone on the internet.",
    evidence: "Bucket name, public-policy flags, public-access-block state.",
    remediation: "Remove public grants and enable S3 Block Public Access.",
    falsePositiveGuard: "Only explicit True flags fire; an unknown/None state is never treated as public.",
  },
  {
    key: "aws_s3_public_acl",
    provider: "aws",
    severity: "critical",
    severityNote: "Critical when public write; high when public read only.",
    title: "AWS S3 bucket ACL grants public access",
    category: "S3 public access",
    confidence: "high",
    metadataOnly: true,
    description: "A bucket ACL grants read or write to AllUsers / AuthenticatedUsers.",
    whatItChecks: "ACL all-users / authenticated-users read & write grants.",
    whyItMatters: "Public ACL grants can expose or allow tampering with objects.",
    evidence: "Bucket name and the specific ACL grant flags.",
    remediation: "Remove public ACL grants; prefer policies and enable Block Public Access.",
    falsePositiveGuard: "Only explicit True grants fire; None is never treated as public.",
  },
  {
    key: "aws_iam_admin_policy_attached",
    provider: "aws",
    severity: "high",
    title: "AWS AdministratorAccess attached to an IAM principal",
    category: "IAM",
    confidence: "high",
    metadataOnly: true,
    description: "The AWS-managed AdministratorAccess policy is attached to a principal.",
    whatItChecks: "Policy attachments whose ARN is exactly arn:aws:iam::aws:policy/AdministratorAccess.",
    whyItMatters: "Over-broad admin grants increase blast radius if the principal is compromised.",
    evidence: "Principal type/name and policy name.",
    remediation: "Replace with least-privilege policies; reserve admin for break-glass roles with MFA.",
    falsePositiveGuard: "Exact ARN match — not a keyword guess.",
  },
  {
    key: "aws_access_key_unused",
    provider: "aws",
    severity: "medium",
    title: "AWS access key is active but unused",
    category: "IAM access keys",
    confidence: "high",
    metadataOnly: true,
    description: "An active access key has not been used in 90+ days.",
    whatItChecks: "Active keys whose last-used age is a concrete value ≥ 90 days.",
    whyItMatters: "Long-lived unused keys are an unnecessary standing credential.",
    evidence: "Username, key id last-4, status, last-used age in days.",
    remediation: "Deactivate then delete; prefer short-lived role credentials.",
    falsePositiveGuard: "An unknown last-used age (never-used vs fetch-failed) is not flagged.",
  },

  // ── Cloudflare ────────────────────────────────────────────────────────────
  {
    key: "cloudflare_ssl_mode_weak",
    provider: "cloudflare",
    severity: "high",
    title: "Cloudflare SSL/TLS mode is weak",
    category: "SSL/TLS",
    confidence: "high",
    metadataOnly: true,
    description: "Zone SSL/TLS mode is 'off' or 'flexible'.",
    whatItChecks: "The zone 'ssl' setting value.",
    whyItMatters: "Traffic to the origin may be sent in cleartext.",
    evidence: "SSL mode value.",
    remediation: "Set SSL/TLS mode to 'Full (strict)'.",
    falsePositiveGuard: "Only off/flexible fire; full/strict are safe.",
  },
  {
    key: "cloudflare_always_https_off",
    provider: "cloudflare",
    severity: "medium",
    title: "Cloudflare 'Always Use HTTPS' is disabled",
    category: "HTTPS",
    confidence: "high",
    metadataOnly: true,
    description: "Plain-HTTP requests are not redirected to HTTPS.",
    whatItChecks: "The 'always_use_https' setting value.",
    whyItMatters: "Visitors may transmit data over an unencrypted connection.",
    evidence: "Setting value.",
    remediation: "Enable 'Always Use HTTPS'.",
    falsePositiveGuard: "Only fires when the value is explicitly 'off'.",
  },
  {
    key: "cloudflare_min_tls_weak",
    provider: "cloudflare",
    severity: "medium",
    title: "Cloudflare minimum TLS version is outdated",
    category: "SSL/TLS",
    confidence: "high",
    metadataOnly: true,
    description: "Minimum TLS version is 1.0 or 1.1.",
    whatItChecks: "The 'min_tls_version' setting value.",
    whyItMatters: "Deprecated TLS versions may weaken transport security.",
    evidence: "Minimum TLS version value.",
    remediation: "Set the minimum TLS version to 1.2 or higher.",
    falsePositiveGuard: "Only 1.0/1.1 fire.",
  },
  {
    key: "cloudflare_security_level_low",
    provider: "cloudflare",
    severity: "medium",
    title: "Cloudflare security level is effectively off",
    category: "WAF / security",
    confidence: "high",
    metadataOnly: true,
    description: "Security level is 'off' or 'essentially_off'.",
    whatItChecks: "The 'security_level' setting value.",
    whyItMatters: "Cloudflare applies little or no challenge to suspicious traffic.",
    evidence: "Security level value.",
    remediation: "Raise the security level to at least 'Medium'.",
    falsePositiveGuard: "low/medium/high are treated as normal; only off/essentially_off fire.",
  },
  {
    key: "cloudflare_development_mode_on",
    provider: "cloudflare",
    severity: "medium",
    title: "Cloudflare development mode is enabled",
    category: "WAF / security",
    confidence: "high",
    metadataOnly: true,
    description: "Development mode bypasses edge cache and some optimizations.",
    whatItChecks: "The 'development_mode' setting value.",
    whyItMatters: "It is meant to be temporary and may reduce protection while active.",
    evidence: "Setting value.",
    remediation: "Turn off development mode when finished.",
    falsePositiveGuard: "Only fires when explicitly 'on'.",
  },
  {
    key: "cloudflare_hsts_disabled",
    provider: "cloudflare",
    severity: "medium",
    title: "Cloudflare HSTS is disabled",
    category: "HTTPS",
    confidence: "high",
    metadataOnly: true,
    description: "HTTP Strict Transport Security is disabled.",
    whatItChecks: "The security_header (HSTS) enabled flag.",
    whyItMatters: "Browsers are not told to use HTTPS, allowing protocol downgrade on first contact.",
    evidence: "HSTS enabled flag.",
    remediation: "Enable HSTS with a reasonable max-age once HTTPS is verified.",
    falsePositiveGuard: "Only an explicit enabled=false fires; indeterminate values are skipped.",
  },
  {
    key: "cloudflare_waf_rule_disabled",
    provider: "cloudflare",
    severity: "high",
    severityNote: "High when a 'block' rule is disabled; medium for challenge rules.",
    title: "Cloudflare WAF rule is disabled",
    category: "WAF / security",
    confidence: "high",
    metadataOnly: true,
    description: "A protective WAF rule (block/challenge) is disabled.",
    whatItChecks: "Per-rule enabled flag for protective actions only.",
    whyItMatters: "The rule no longer blocks or challenges matching traffic.",
    evidence: "Rule description, action, enabled flag, ruleset id (never the expression).",
    remediation: "Re-enable the rule or document why it is intentionally off.",
    falsePositiveGuard: "Disabled log/skip rules are ignored — only protective actions fire.",
  },
  {
    key: "cloudflare_dns_private_origin",
    provider: "cloudflare",
    severity: "high",
    title: "Cloudflare DNS record points to a private or reserved IP",
    category: "DNS",
    confidence: "high",
    metadataOnly: true,
    description: "A public A/AAAA record resolves to a private/loopback/reserved IP.",
    whatItChecks: "A/AAAA record content classified via IP-address rules.",
    whyItMatters: "Usually a misconfiguration that may break routing or leak internal network details.",
    evidence: "Record name, type, content, address kind, proxied flag.",
    remediation: "Point the record at the correct public address or remove it.",
    falsePositiveGuard: "Public/global IPs are normal and never flagged; CNAMEs/non-IP content are ignored.",
  },

  // ── Supabase ──────────────────────────────────────────────────────────────
  {
    key: "supabase_rls_disabled",
    provider: "supabase",
    severity: "high",
    title: "Supabase table has Row Level Security disabled",
    category: "RLS",
    confidence: "high",
    metadataOnly: true,
    description: "Row Level Security is disabled on a table.",
    whatItChecks: "The rls_enabled flag per table.",
    whyItMatters: "Without RLS, rows may be broadly readable or writable by any role that can reach the table.",
    evidence: "Schema and table name.",
    remediation: "Enable RLS and add explicit policies.",
    falsePositiveGuard: "Only an explicit rls_enabled=false fires; missing/unknown is skipped.",
  },
  {
    key: "supabase_anonymous_access_enabled",
    provider: "supabase",
    severity: "medium",
    title: "Supabase anonymous sign-ins are enabled",
    category: "Auth",
    confidence: "medium",
    metadataOnly: true,
    description: "Anonymous authentication is enabled.",
    whatItChecks: "The auth-config anonymous_enabled flag.",
    whyItMatters: "Combined with weak/missing RLS, this may allow unauthenticated data access.",
    evidence: "anonymous_enabled flag.",
    remediation: "Disable anonymous sign-ins if not required; otherwise scope RLS tightly.",
    falsePositiveGuard: "Medium severity and careful wording — anonymous auth is a feature, risky mainly with weak RLS.",
  },
  {
    key: "supabase_jwt_expiry_long",
    provider: "supabase",
    severity: "medium",
    title: "Supabase JWT expiry is very long",
    category: "Auth",
    confidence: "high",
    metadataOnly: true,
    description: "The JWT access-token lifetime is over a day.",
    whatItChecks: "auth-config jwt_exp as a concrete integer > 86400 seconds.",
    whyItMatters: "Long-lived tokens stay valid after sign-out and widen the impact of a leaked token.",
    evidence: "JWT expiry in seconds.",
    remediation: "Shorten the access-token lifetime; rely on refresh-token rotation.",
    falsePositiveGuard: "Only a concrete int over the threshold fires; non-int/None is skipped.",
  },
  {
    key: "supabase_public_select_sensitive_table",
    provider: "supabase",
    severity: "high",
    title: "Supabase public read policy on a sensitive-looking table",
    category: "RLS",
    confidence: "high",
    metadataOnly: true,
    description: "A policy targeting the public/anon role allows SELECT on a table whose name suggests sensitive data. May expose data depending on grants and application access.",
    whatItChecks: "pg_policies metadata (role targets + command) for an active public/anon SELECT policy on an RLS-enabled, sensitively-named table. Never the policy expression, columns, or rows.",
    whyItMatters: "Public read access to sensitive data may increase unauthorized-access risk.",
    evidence: "Schema/table name and a policy count (never the policy expression or row data).",
    remediation: "Scope reads to authenticated, row-scoped policies instead of the public/anon role.",
    falsePositiveGuard: "Only fires when a public/anon SELECT policy is active on an RLS-enabled, sensitively-named table.",
  },
  {
    key: "supabase_public_write_policy",
    provider: "supabase",
    severity: "high",
    title: "Supabase public write policy on a table",
    category: "RLS",
    confidence: "high",
    metadataOnly: true,
    description: "A policy targeting the public/anon role allows insert, update, or delete on a table. May allow broad writes depending on grants and application access.",
    whatItChecks: "pg_policies metadata (role targets + command) for an active public/anon write policy on an RLS-enabled table. Never the policy expression, columns, or rows.",
    whyItMatters: "Public write access may increase unauthorized-access risk to the data.",
    evidence: "Schema/table name and a policy count (never the policy expression or row data).",
    remediation: "Scope writes to authenticated, ownership-checked policies instead of the public/anon role.",
    falsePositiveGuard: "Only fires when a public/anon insert/update/delete policy is active on an RLS-enabled table.",
  },
  {
    key: "supabase_edge_function_jwt_disabled",
    provider: "supabase",
    severity: "medium",
    title: "Supabase Edge Function has JWT verification disabled",
    category: "Edge Functions",
    confidence: "high",
    metadataOnly: true,
    description: "An Edge Function has verify_jwt disabled, so it accepts unauthenticated requests. Severity is higher for sensitive-looking function names.",
    whatItChecks: "Edge Function metadata verify_jwt flag (and the function name for severity).",
    whyItMatters: "An unauthenticated function may increase unauthorized-access risk depending on what it does.",
    evidence: "Function name and the verify_jwt boolean (never source code or secrets).",
    remediation: "Enable JWT verification unless the function is intentionally public; add in-function authorization.",
    falsePositiveGuard: "Only an explicit verify_jwt=false fires; missing/unknown is skipped.",
  },
  {
    key: "supabase_auth_protection_missing",
    provider: "supabase",
    severity: "medium",
    title: "Supabase leaked-password protection is disabled",
    category: "Auth",
    confidence: "medium",
    metadataOnly: true,
    description: "Leaked-password protection (Have I Been Pwned) is disabled, so users may set known-compromised passwords. Notes MFA status when also disabled.",
    whatItChecks: "auth-config leaked_password_protection_enabled (and mfa_totp_enabled for context).",
    whyItMatters: "Allowing known-leaked passwords may increase unauthorized-access risk.",
    evidence: "The two protection booleans (no auth user data).",
    remediation: "Enable leaked-password protection and consider enabling/encouraging MFA.",
    falsePositiveGuard: "Only an explicit leaked-password-protection=false fires; missing/unknown is skipped.",
  },

  // ── Firebase ──────────────────────────────────────────────────────────────
  {
    key: "firebase_rules_public",
    provider: "firebase",
    severity: "critical",
    severityNote: "Critical when public write; high when public read only.",
    title: "Firebase Firestore rules allow public access",
    category: "Security rules",
    confidence: "medium",
    metadataOnly: true,
    description: "The active Firestore ruleset appears to allow public read/write.",
    whatItChecks: "public_read_detected / public_write_detected on the Firestore ruleset.",
    whyItMatters: "Documents may be exposed to unauthenticated reads or writes.",
    evidence: "Release name, public read/write flags, parser confidence (never raw rules).",
    remediation: "Replace broad 'allow if true' rules with auth-scoped checks.",
    falsePositiveGuard: "Low-confidence parses are skipped to avoid false positives.",
  },
  {
    key: "firebase_storage_rules_public",
    provider: "firebase",
    severity: "critical",
    severityNote: "Critical when public write; high when public read only.",
    title: "Firebase Storage rules allow public access",
    category: "Security rules",
    confidence: "medium",
    metadataOnly: true,
    description: "The active Storage ruleset appears to allow public read/write.",
    whatItChecks: "public_read_detected / public_write_detected on the Storage ruleset.",
    whyItMatters: "Stored objects may be exposed to unauthenticated access.",
    evidence: "Release name, public read/write flags, parser confidence.",
    remediation: "Tighten Storage rules to require auth and scope to owners.",
    falsePositiveGuard: "Low-confidence parses are skipped.",
  },
  {
    key: "firebase_anonymous_auth_enabled",
    provider: "firebase",
    severity: "medium",
    title: "Firebase anonymous authentication is enabled",
    category: "Auth",
    confidence: "medium",
    metadataOnly: true,
    description: "Anonymous authentication is enabled.",
    whatItChecks: "The auth-config anonymous_enabled flag.",
    whyItMatters: "With permissive rules, this may allow unauthenticated users to access data.",
    evidence: "Project id and anonymous_enabled flag.",
    remediation: "Disable anonymous auth if not required; otherwise scope rules tightly.",
    falsePositiveGuard: "Medium severity — risky mainly when paired with permissive rules.",
  },
  {
    key: "firebase_database_public_read",
    provider: "firebase",
    severity: "high",
    title: "Firebase Realtime Database rules allow public read",
    category: "Security rules",
    confidence: "high",
    metadataOnly: true,
    description: "The Realtime Database rules appear to allow public (unauthenticated) read.",
    whatItChecks: "public_read_detected on the Realtime Database ruleset (.read expressions).",
    whyItMatters: "Data may be exposed depending on rule evaluation and application access patterns.",
    evidence: "Instance name hash, public-read flag, parser confidence (never raw rules JSON).",
    remediation: "Replace '.read': true with auth-scoped expressions (e.g. auth != null).",
    falsePositiveGuard: "Only an unconditional '.read': true with no auth guard fires; low-confidence parses are skipped.",
  },
  {
    key: "firebase_database_public_write",
    provider: "firebase",
    severity: "critical",
    title: "Firebase Realtime Database rules allow public write",
    category: "Security rules",
    confidence: "high",
    metadataOnly: true,
    description: "The Realtime Database rules appear to allow public (unauthenticated) write.",
    whatItChecks: "public_write_detected on the Realtime Database ruleset (.write expressions).",
    whyItMatters: "May expose data and may increase unauthorized-access risk depending on rule evaluation.",
    evidence: "Instance name hash, public-write flag, parser confidence (never raw rules JSON).",
    remediation: "Replace '.write': true with auth-scoped, ownership-checked expressions.",
    falsePositiveGuard: "Only an unconditional '.write': true with no auth guard fires; low-confidence parses are skipped.",
  },
  {
    key: "firebase_auth_protection_missing",
    provider: "firebase",
    severity: "medium",
    title: "Firebase multi-factor authentication is not enabled",
    category: "Auth",
    confidence: "medium",
    metadataOnly: true,
    description: "MFA is not enabled for the project's Authentication configuration.",
    whatItChecks: "The auth-config mfa_enabled flag.",
    whyItMatters: "Single-factor accounts may increase unauthorized-access risk.",
    evidence: "Project id and mfa_enabled flag.",
    remediation: "Enable multi-factor authentication for Firebase Auth.",
    falsePositiveGuard: "Only an explicit mfa_enabled=false fires; missing/unknown is skipped.",
  },

  // ── Stripe ────────────────────────────────────────────────────────────────
  {
    key: "stripe_webhook_http",
    provider: "stripe",
    severity: "critical",
    title: "Stripe webhook uses plain HTTP",
    category: "Webhooks",
    confidence: "high",
    metadataOnly: true,
    description: "An enabled Stripe webhook endpoint delivers over plain HTTP.",
    whatItChecks: "The endpoint URL scheme for enabled webhook endpoints.",
    whyItMatters: "Event payloads and signature headers may be transmitted in cleartext.",
    evidence: "Endpoint delivery URL.",
    remediation: "Update the endpoint to https:// and verify signature checks still pass.",
    falsePositiveGuard: "Disabled endpoints are not flagged.",
  },
  {
    key: "stripe_webhook_disabled",
    provider: "stripe",
    severity: "medium",
    title: "Stripe webhook endpoint is disabled",
    category: "Webhooks",
    confidence: "high",
    metadataOnly: true,
    description: "A Stripe webhook endpoint is disabled and is not receiving events.",
    whatItChecks: "The endpoint status for webhook endpoints.",
    whyItMatters: "Downstream automation may miss payment/subscription events, which may affect billing/payment operations.",
    evidence: "Endpoint status (disabled).",
    remediation: "Confirm whether the endpoint should be enabled; re-enable or remove it.",
    falsePositiveGuard: "Only an explicit status='disabled' fires; enabled/unknown is skipped.",
  },
  {
    key: "stripe_webhook_broad_events",
    provider: "stripe",
    severity: "medium",
    title: "Stripe webhook subscribes to a very broad set of events",
    category: "Webhooks",
    confidence: "medium",
    metadataOnly: true,
    description: "An enabled webhook subscribes to all events ('*') or a very large number of event types.",
    whatItChecks: "The enabled_events list for enabled endpoints (wildcard or a large count).",
    whyItMatters: "Receiving more events than needed widens the configuration surface and may increase webhook configuration risk.",
    evidence: "Subscribed-event count and whether the wildcard '*' is used (never payloads).",
    remediation: "Scope the webhook to only the events the integration needs.",
    falsePositiveGuard: "Fires on the wildcard '*' or a large explicit event count; a normal scoped list is not flagged.",
  },
  {
    key: "stripe_payment_link_tax_disabled",
    provider: "stripe",
    severity: "medium",
    title: "Stripe payment link has automatic tax disabled",
    category: "Payment links",
    confidence: "high",
    metadataOnly: true,
    description: "An active Stripe payment link does not have automatic tax enabled.",
    whatItChecks: "automatic_tax_enabled on active payment links.",
    whyItMatters: "Tax may not be collected correctly, which may affect billing/payment operations and tax compliance.",
    evidence: "active and automatic_tax_enabled flags (never customer or payment data).",
    remediation: "Enable automatic tax on the link if collection is expected for your markets.",
    falsePositiveGuard: "Only an active link with an explicit automatic_tax_enabled=false fires.",
  },
  {
    key: "stripe_payment_link_promo_codes_enabled",
    provider: "stripe",
    severity: "low",
    title: "Stripe payment link allows promotion codes",
    category: "Payment links",
    confidence: "high",
    metadataOnly: true,
    description: "An active Stripe payment link allows customers to enter promotion codes.",
    whatItChecks: "allow_promotion_codes on active payment links.",
    whyItMatters: "If unintended, this may allow unexpected discounting and may affect billing/payment operations.",
    evidence: "active and allow_promotion_codes flags.",
    remediation: "Disable promotion codes on the link if it is not intended.",
    falsePositiveGuard: "Only an active link with an explicit allow_promotion_codes=true fires; a config-review item, not an exposure.",
  },
  {
    key: "stripe_portal_subscription_cancel_enabled",
    provider: "stripe",
    severity: "low",
    title: "Stripe customer portal allows self-serve cancellation",
    category: "Customer portal",
    confidence: "high",
    metadataOnly: true,
    description: "The active customer portal configuration lets customers cancel their own subscriptions.",
    whatItChecks: "subscription_cancel_enabled on active billing portal configurations.",
    whyItMatters: "If unintended, self-serve cancellation may affect billing/payment operations and retention.",
    evidence: "active and subscription_cancel_enabled flags.",
    remediation: "Disable self-serve cancellation or add a cancellation flow if it is not intended.",
    falsePositiveGuard: "Only an active portal config with an explicit subscription_cancel_enabled=true fires.",
  },
  {
    key: "stripe_portal_login_enabled",
    provider: "stripe",
    severity: "medium",
    title: "Stripe customer portal login page is enabled",
    category: "Customer portal",
    confidence: "high",
    metadataOnly: true,
    description: "The active customer portal configuration has its hosted login page enabled.",
    whatItChecks: "login_page_enabled on active billing portal configurations.",
    whyItMatters: "Customers can request a portal session by email; if unintended this widens the self-serve access surface.",
    evidence: "active and login_page_enabled flags.",
    remediation: "Disable the hosted login page if portal sessions should only be created by your app.",
    falsePositiveGuard: "Only an active portal config with an explicit login_page_enabled=true fires.",
  },
  {
    key: "stripe_account_capability_incomplete",
    provider: "stripe",
    severity: "medium",
    title: "Stripe account is not fully enabled for payments",
    category: "Account",
    confidence: "high",
    metadataOnly: true,
    description: "Charges, payouts, or required-information onboarding are not complete for the account.",
    whatItChecks: "charges_enabled / payouts_enabled / details_submitted on account settings.",
    whyItMatters: "The account may be unable to accept charges or receive payouts, which may affect billing/payment operations.",
    evidence: "charges_enabled, payouts_enabled, details_submitted booleans.",
    remediation: "Complete the account's required information in the Stripe dashboard.",
    falsePositiveGuard: "Only an explicit charges/payouts/details flag of false fires; missing/unknown is skipped.",
  },

  // ── Vercel ────────────────────────────────────────────────────────────────
  {
    key: "vercel_preview_unprotected",
    provider: "vercel",
    severity: "medium",
    title: "Vercel preview deployments are not protected",
    category: "Deployment protection",
    confidence: "medium",
    metadataOnly: true,
    description: "Preview deployments have no Vercel Authentication, password, or preview protection.",
    whatItChecks: "deployment-protection flags: preview protection, SSO, password all off.",
    whyItMatters: "Preview URLs may be publicly accessible and could expose unreleased features or non-production data.",
    evidence: "Project name and the (empty) set of active protections.",
    remediation: "Enable Vercel Authentication or password protection for previews.",
    falsePositiveGuard: "Only fires when every protection mechanism is off; previews are not production data, so severity is medium.",
  },
  {
    key: "vercel_production_branch_missing",
    provider: "vercel",
    severity: "medium",
    title: "Vercel project has no production branch configured",
    category: "Deployment configuration",
    confidence: "medium",
    metadataOnly: true,
    description: "A git-connected project has no production branch set, so production deployments may track an unexpected branch.",
    whatItChecks: "Project git connection plus whether a production branch is configured.",
    whyItMatters: "An unset production branch can cause unintended code to ship to production.",
    evidence: "Project name and a boolean indicating the production branch is unset.",
    remediation: "Set an explicit production branch (for example, main or master) in the project's Git settings.",
    falsePositiveGuard: "Only fires when a git repository is connected but no production branch is configured.",
  },
  {
    key: "vercel_production_branch_unusual",
    provider: "vercel",
    severity: "medium",
    title: "Vercel production branch looks non-production",
    category: "Deployment configuration",
    confidence: "medium",
    metadataOnly: true,
    description: "The production branch matches a conventionally non-production name (dev, staging, preview, etc.).",
    whatItChecks: "The configured production branch name against a list of known non-production names.",
    whyItMatters: "Production deployments may track development or staging code.",
    evidence: "Project name and the production branch name.",
    remediation: "Confirm the production branch is intentional; point it at your release branch if not.",
    falsePositiveGuard: "main/master/prod/production are treated as normal; only known non-production names fire.",
  },
  {
    key: "vercel_domain_unverified",
    provider: "vercel",
    severity: "medium",
    title: "Vercel domain is not verified",
    category: "Domains",
    confidence: "medium",
    metadataOnly: true,
    description: "A domain attached to the project is not verified, which can indicate an incomplete or stale domain configuration.",
    whatItChecks: "Each custom domain's verification status.",
    whyItMatters: "Unverified domains may not serve traffic correctly and can signal stale configuration.",
    evidence: "Domain name and a boolean indicating it is unverified.",
    remediation: "Complete DNS verification or remove the domain if it is no longer used.",
    falsePositiveGuard: "Only an explicit verified=false fires; verified or unknown domains are skipped.",
  },
  {
    key: "vercel_env_var_broad_target",
    provider: "vercel",
    severity: "medium",
    title: "Vercel env var spans production and non-production",
    category: "Environment variables",
    confidence: "medium",
    metadataOnly: true,
    description: "An environment variable is targeted at production and at least one non-production environment, suggesting a shared value across environments.",
    whatItChecks: "The set of target environments (production / preview / development) on each env var. Values are never read.",
    whyItMatters: "A single value shared across environments increases production-change risk.",
    evidence: "Env var key name and its target environment list (never the value).",
    remediation: "Use environment-specific values where production and non-production should differ.",
    falsePositiveGuard: "Only fires when one variable spans production and a non-production environment.",
  },
  {
    key: "vercel_sensitive_env_var_broad_scope",
    provider: "vercel",
    severity: "high",
    title: "Sensitive-looking Vercel env var is broadly scoped",
    category: "Environment variables",
    confidence: "high",
    metadataOnly: true,
    description: "An env var with a secret-suggestive key name (secret/token/key/password/webhook/signing/db) is scoped to a non-production environment. Its metadata suggests broad scope.",
    whatItChecks: "The env var KEY name pattern plus its target environments. The value is never read or stored.",
    whyItMatters: "A secret-suggestive variable exposed beyond production may widen where that value is used.",
    evidence: "Env var key name and its target environment list (never the value).",
    remediation: "Scope sensitive variables to production only, and use separate non-production values.",
    falsePositiveGuard: "Only fires when a secret-suggestive key name is also scoped to a non-production environment; the value is never read.",
  },
  {
    key: "vercel_deploy_hook_production_branch",
    provider: "vercel",
    severity: "medium",
    title: "Vercel deploy hook targets the production branch",
    category: "Deploy hooks",
    confidence: "medium",
    metadataOnly: true,
    description: "A deploy hook targets the production branch. A deploy hook may allow a production deployment if its URL is invoked.",
    whatItChecks: "Each deploy hook's target git ref against known production branch names. The hook URL is never stored.",
    whyItMatters: "A production-targeting deploy hook can trigger production deployments if its URL is known.",
    evidence: "Deploy hook name and target ref (never the hook URL).",
    remediation: "Confirm production deploy hooks are intended and keep their URLs secret; remove unused hooks.",
    falsePositiveGuard: "Only fires when a deploy hook's target ref is the production branch; the hook URL is never stored.",
  },

  // ── Shopify ───────────────────────────────────────────────────────────────
  {
    key: "shopify_webhook_http",
    provider: "shopify",
    severity: "critical",
    title: "Shopify webhook uses plain HTTP",
    category: "Webhooks",
    confidence: "high",
    metadataOnly: true,
    description: "A Shopify webhook delivers to a plain-HTTP endpoint.",
    whatItChecks: "The webhook endpoint scheme.",
    whyItMatters: "Event payloads and HMAC headers may be transmitted in cleartext.",
    evidence: "Webhook topic, endpoint domain, scheme (path is hashed, never stored).",
    remediation: "Switch the webhook endpoint to HTTPS and re-verify HMAC.",
    falsePositiveGuard: "Only an explicit http scheme fires; non-HTTP transports (EventBridge/Pub-Sub) are ignored.",
  },
];

// ── Deferred / planned coverage (clearly NOT active) ─────────────────────────

export const DEFERRED_RULES: DeferredRuleMeta[] = [
  {
    provider: "supabase",
    title: "Public storage bucket",
    reason: "Listing storage buckets and their public/private status requires the project's service-role/anon key, which ConfigTrace deliberately does not store or use. The Management API exposes no safe bucket list.",
  },
  {
    provider: "supabase",
    title: "Auth redirect URL too broad",
    reason: "The connector stores only the count of additional redirect URLs (never the raw URLs/patterns), so wildcard/localhost cannot be evaluated.",
  },
  {
    provider: "firebase",
    title: "Firestore / Storage public read vs write split",
    reason: "firebase_rules_public and firebase_storage_rules_public already detect public access and raise severity to critical for public write; separate per-operation read/write keys would double-flag the identical ruleset state.",
  },
  {
    provider: "firebase",
    title: "Public HTTPS Cloud Function",
    reason: "The function metadata record carries the trigger type (HTTP) but no ingress-settings or unauthenticated-invoker field, so public reachability cannot be reliably inferred without unsafe IAM-policy reads.",
  },
  {
    provider: "cloudflare",
    title: "Unproxied DNS for sensitive hostnames",
    reason:
      "Many DNS-only records are intentional (MX, TXT, mail, verification, third-party CNAMEs); flagging them needs an expected-proxy baseline.",
  },
  {
    provider: "aws",
    title: "Public web ports (80/443)",
    reason:
      "Public 80/443 is normal for web servers; without reachability/attachment context, flagging it would be noise.",
  },
  {
    provider: "aws",
    title: "Default security group public ingress",
    reason: "Requires joining a rule to its parent group's name, which the per-rule record does not carry.",
  },
  {
    provider: "stripe",
    title: "Restricted key scope expansion / live-mode webhook",
    reason:
      "The connector does not (and cannot safely) enumerate other API keys' scopes, and webhook records have no live/test mode field.",
  },
  {
    provider: "stripe",
    title: "Separate insecure-webhook-URL rule",
    reason:
      "stripe_webhook_http already fires on an enabled plain-HTTP webhook endpoint; a separate insecure-URL key would double-flag the identical state.",
  },
  {
    provider: "stripe",
    title: "Standalone Tax-settings rule",
    reason:
      "Tax posture is reviewed per active payment link via stripe_payment_link_tax_disabled; the account-singleton Stripe Tax settings surface is not fetched, so no separate key is added.",
  },
  {
    provider: "github",
    title: "Repository public visibility",
    reason: "There is no expected-private signal, so flagging public repos would be wrong.",
  },
  {
    provider: "github",
    title: "Broad Actions permissions",
    reason: "allowed_actions='all' is GitHub's common default and is too low-signal to call an exposure.",
  },
  {
    provider: "vercel",
    title: "Deploy hooks exposed (existence alone)",
    reason: "Every deploy hook is an unauthenticated trigger by design; mere existence is not a reliable exposure. Only hooks targeting the production branch are flagged (vercel_deploy_hook_production_branch).",
  },
  {
    provider: "vercel",
    title: "Project / deployment protection missing",
    reason: "The vercel_deployment_protection record already drives vercel_preview_unprotected when every protection is off; a separate 'protection missing' rule would double-flag the identical state.",
  },
  {
    provider: "shopify",
    title: "Dangerous app scopes",
    reason: "Scope presence is normal for legitimate apps; flagging needs an expected-scope baseline to avoid noise.",
  },
];

// ── Provider coverage summary ────────────────────────────────────────────────

export const PROVIDER_COVERAGE: ProviderCoverage[] = [
  { provider: "github", surfaces: ["Branch protection", "Webhooks", "Deploy keys", "Environment protection"] },
  { provider: "aws", surfaces: ["Security groups", "S3 public access", "IAM administrator policy", "Stale access keys"] },
  { provider: "cloudflare", surfaces: ["SSL/TLS", "HTTPS", "WAF", "HSTS", "Development mode", "Private-origin DNS"] },
  { provider: "supabase", surfaces: ["Row Level Security", "Public table policies", "Anonymous access", "JWT expiry", "Edge Functions"] },
  { provider: "firebase", surfaces: ["Firestore rules", "Realtime Database rules", "Storage rules", "Anonymous auth", "MFA"] },
  { provider: "stripe", surfaces: ["Webhook HTTPS", "Webhook posture", "Payment links", "Customer portal", "Account payments readiness"] },
  { provider: "vercel", surfaces: ["Preview protection", "Production branch", "Domains", "Environment variables", "Deploy hooks"] },
  { provider: "shopify", surfaces: ["Webhook HTTPS"] },
];
