"""GitHub App utilities — M31.

Provides:
  - HMAC-SHA256 stateless state tokens (CSRF protection for the install flow)
  - GitHub App JWT minting  (RS256, 10-minute lifetime)
  - Installation token minting  (short-lived, never persisted or logged)
  - Repository listing for an installation

Security constraints
--------------------
* The GitHub App private key is NEVER logged or included in any exception message.
* Installation access tokens are NEVER stored, logged, or returned in any API response.
* State tokens are HMAC-signed and expire in 10 minutes.
* State tokens bind to the requesting user_id; a mismatch is treated as an attack.

Environment variables required
-------------------------------
  GITHUB_APP_ID               — Numeric App ID from GitHub App settings
  GITHUB_APP_SLUG             — Slug used in the install URL (e.g. "configtrace")
  GITHUB_APP_PRIVATE_KEY      — Base64-encoded PEM or literal PEM of the App private key
  GITHUB_APP_OAUTH_STATE_SECRET — Random 32+ byte secret for HMAC state tokens
"""

from __future__ import annotations

import base64
import hashlib
import hmac as hmac_lib
import json
import logging
import secrets
import time
from typing import Any

import httpx

logger = logging.getLogger(__name__)

_GITHUB_API_BASE = "https://api.github.com"
_APP_JWT_LIFETIME = 600   # 10 minutes — GitHub's maximum
_STATE_TOKEN_TTL = 600    # 10 minutes
_REQUEST_TIMEOUT = 30.0   # seconds


# ── Private key decoding ──────────────────────────────────────────────────────

def decode_private_key(raw: str) -> str:
    """Accept a base64-encoded PEM or a literal PEM string.

    Render injects multiline PEM as a single-line environment variable,
    mangling newlines.  The recommended workaround is to base64-encode the key
    before storing it in Render, then decode it here.

    The raw value may be:
      * Base64-encoded PEM (preferred for Render) — decoded first.
      * Literal PEM (local .env files, legacy configs).

    Raises:
        ValueError: If the result does not look like a PEM private key.
                    The error message is safe to surface to operators; it does
                    NOT include the key value.
    """
    stripped = raw.strip()
    # Attempt base64 decode first (handles Render's env var injection).
    # Python's b64decode ignores whitespace, so base64 strings that have
    # embedded newlines (e.g. from `base64` without -w 0) still decode.
    try:
        decoded = base64.b64decode(stripped).decode("utf-8")
        if "-----BEGIN" in decoded and "PRIVATE KEY" in decoded:
            return decoded
    except Exception:
        pass
    # Fall back: treat as literal PEM.
    if "-----BEGIN" in stripped and "PRIVATE KEY" in stripped:
        return stripped
    raise ValueError(
        "GitHub App private key could not be parsed. "
        "GITHUB_APP_PRIVATE_KEY must be a PEM private key or its base64-encoded form. "
        "To encode: base64 -w 0 private-key.pem  (Linux) "
        "or base64 -i private-key.pem | tr -d '\\n'  (macOS). "
        "Never paste the raw PEM into Render — newlines are mangled."
    )


# ── HMAC state tokens ─────────────────────────────────────────────────────────

def generate_state_token(
    user_id: str,
    secret: str,
    ttl_seconds: int = _STATE_TOKEN_TTL,
) -> str:
    """Generate a stateless HMAC-SHA256 state token bound to *user_id*.

    Format:  ``<base64url-payload>.<hmac-hex>``

    The payload is a JSON object with ``user_id``, ``nonce``, and
    ``expires_at`` (Unix timestamp).  The HMAC is computed over the raw
    base64url string.

    Args:
        user_id:     The Clerk user UUID (string form) to bind this token to.
        secret:      GITHUB_APP_OAUTH_STATE_SECRET — random byte string.
        ttl_seconds: Token lifetime in seconds (default 10 minutes).

    Returns:
        A URL-safe state token string.
    """
    payload: dict[str, Any] = {
        "user_id": user_id,
        "nonce": secrets.token_hex(16),
        "expires_at": int(time.time()) + ttl_seconds,
    }
    payload_bytes = json.dumps(payload, separators=(",", ":")).encode()
    # rstrip "=" — URL-safe base64 without padding
    payload_b64 = base64.urlsafe_b64encode(payload_bytes).decode().rstrip("=")
    sig = hmac_lib.new(
        secret.encode(),
        payload_b64.encode(),
        hashlib.sha256,
    ).hexdigest()
    return f"{payload_b64}.{sig}"


def verify_state_token(token: str, user_id: str, secret: str) -> dict:
    """Verify a state token generated by :func:`generate_state_token`.

    Checks HMAC, expiry, and user_id binding in constant time.

    Args:
        token:   State token from the GitHub redirect URL query parameter.
        user_id: The Clerk user UUID (string form) of the requesting user.
        secret:  GITHUB_APP_OAUTH_STATE_SECRET — must match the signing secret.

    Returns:
        The decoded payload dict on success.

    Raises:
        ValueError: On any validation failure (invalid format, bad HMAC,
                    expired token, or user_id mismatch).  The message is
                    intentionally vague to avoid leaking information.
    """
    parts = token.split(".", 1)
    if len(parts) != 2:
        raise ValueError("Invalid state token.")

    payload_b64, provided_sig = parts

    expected_sig = hmac_lib.new(
        secret.encode(),
        payload_b64.encode(),
        hashlib.sha256,
    ).hexdigest()
    if not hmac_lib.compare_digest(expected_sig, provided_sig):
        raise ValueError("Invalid state token.")

    try:
        # Re-add base64 padding stripped during generation.
        padding = "=" * (-len(payload_b64) % 4)
        payload_bytes = base64.urlsafe_b64decode(payload_b64 + padding)
        payload = json.loads(payload_bytes.decode())
    except Exception:
        raise ValueError("Invalid state token.")

    if payload.get("expires_at", 0) < int(time.time()):
        raise ValueError("State token expired.")

    if payload.get("user_id") != user_id:
        # Bind mismatch — potential CSRF attack or session mixup.
        raise ValueError("Invalid state token.")

    return payload


# ── GitHub App JWT ────────────────────────────────────────────────────────────

def mint_app_jwt(app_id: str, private_key_pem: str) -> str:
    """Mint a short-lived GitHub App JWT (RS256).

    The JWT is signed with the App's RSA private key and authenticates
    requests as the App itself (not as a user or installation).  It has
    a 10-minute lifetime — the GitHub-enforced maximum.

    The ``iat`` is backdated 60 seconds to account for clock drift between
    servers (GitHub's recommendation).

    Args:
        app_id:          GitHub App numeric ID (string or int accepted).
        private_key_pem: Decoded RSA private key in PEM format.
                         **Never log this value.**

    Returns:
        A signed JWT string.

    Raises:
        RuntimeError: If signing fails.  The private key is NOT included in
                      the exception message.
    """
    from jose import jwt  # python-jose[cryptography]==3.3.0

    now = int(time.time())
    payload = {
        "iat": now - 60,           # backdate 60 s for clock drift
        "exp": now + _APP_JWT_LIFETIME,
        "iss": str(app_id),
    }
    try:
        return jwt.encode(payload, private_key_pem, algorithm="RS256")
    except Exception as exc:
        # Re-raise without embedding the private key in the message.
        raise RuntimeError(f"Failed to mint GitHub App JWT: {exc}") from exc


# ── GitHub API helpers ────────────────────────────────────────────────────────

def _safe_github_message(resp: "httpx.Response") -> str:
    """Extract GitHub's 'message' field from an error response body.

    GitHub error responses have the shape ``{"message": "...", ...}``.
    This field never contains secrets so it is safe to log and surface.
    Returns an empty string if the body cannot be parsed.
    """
    try:
        body = resp.json()
        msg = body.get("message", "")
        return str(msg) if msg else ""
    except Exception:
        return ""


# ── Installation token ────────────────────────────────────────────────────────

def mint_installation_token(installation_id: int, app_jwt: str) -> str:
    """Mint a short-lived installation access token (~1 hour lifetime).

    Uses the GitHub App JWT to authenticate a
    ``POST /app/installations/{id}/access_tokens`` call and returns the
    token string.

    Security guarantees:
    * The token is NEVER logged by this function.
    * The caller MUST NOT log or persist the returned token.
    * The token is valid for approximately 1 hour; GitHub may revoke it earlier.

    Args:
        installation_id: The GitHub App installation ID (integer).
        app_jwt:         A valid GitHub App JWT.  **Never log this value.**

    Returns:
        An installation access token string.

    Raises:
        RuntimeError: On GitHub API error or network failure.
    """
    url = f"{_GITHUB_API_BASE}/app/installations/{installation_id}/access_tokens"
    headers = {
        "Authorization": f"Bearer {app_jwt}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    try:
        with httpx.Client(timeout=_REQUEST_TIMEOUT) as client:
            resp = client.post(url, headers=headers)
    except httpx.RequestError as exc:
        raise RuntimeError(
            f"Network error minting installation token: {exc}"
        ) from exc

    if resp.status_code == 201:
        # NOTE: do not log resp.json() — it contains the token.
        return resp.json()["token"]

    # Extract GitHub's human-readable error message — safe to surface.
    gh_msg = _safe_github_message(resp)
    gh_suffix = f": {gh_msg}" if gh_msg else ""

    if resp.status_code in (401, 403):
        raise RuntimeError(
            f"GitHub App authentication failed minting installation token "
            f"(HTTP {resp.status_code}{gh_suffix}). "
            "Verify GITHUB_APP_ID and GITHUB_APP_PRIVATE_KEY are correct."
        )
    raise RuntimeError(
        f"Failed to mint installation token: "
        f"GitHub returned HTTP {resp.status_code}{gh_suffix}."
    )


# ── Repository listing ────────────────────────────────────────────────────────

def list_installation_repos(installation_id: int, app_jwt: str) -> list[dict]:
    """List all repositories accessible to a GitHub App installation.

    Mints a short-lived installation token (discarded after the call), then
    fetches all pages from ``GET /installation/repositories``.

    Args:
        installation_id: The GitHub App installation ID.
        app_jwt:         A valid GitHub App JWT.

    Returns:
        List of repository dicts, each with:
          ``full_name``, ``owner`` (login), ``name``, ``private``,
          ``description``

    Raises:
        RuntimeError: On token minting failure or GitHub API error.
    """
    # Mint an ephemeral installation token — never log or persist.
    install_token = mint_installation_token(installation_id, app_jwt)

    headers = {
        "Authorization": f"Bearer {install_token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    repos: list[dict] = []
    page = 1
    per_page = 100

    try:
        with httpx.Client(timeout=_REQUEST_TIMEOUT) as client:
            while True:
                resp = client.get(
                    f"{_GITHUB_API_BASE}/installation/repositories",
                    headers=headers,
                    params={"per_page": per_page, "page": page},
                )
                if resp.status_code in (401, 403):
                    gh_msg = _safe_github_message(resp)
                    gh_suffix = f": {gh_msg}" if gh_msg else ""
                    raise RuntimeError(
                        f"Installation token rejected by GitHub "
                        f"(HTTP {resp.status_code}{gh_suffix})."
                    )
                if not resp.is_success:
                    gh_msg = _safe_github_message(resp)
                    gh_suffix = f": {gh_msg}" if gh_msg else ""
                    raise RuntimeError(
                        f"GitHub API error listing repos "
                        f"(HTTP {resp.status_code}{gh_suffix})."
                    )
                body = resp.json()
                page_repos: list[dict] = body.get("repositories", [])
                for r in page_repos:
                    repos.append({
                        "full_name":   r.get("full_name", ""),
                        "owner":       (r.get("owner") or {}).get("login", ""),
                        "name":        r.get("name", ""),
                        "private":     bool(r.get("private", False)),
                        "description": r.get("description"),
                    })
                if len(page_repos) < per_page:
                    break
                total = body.get("total_count", 0)
                if len(repos) >= total:
                    break
                page += 1
    except RuntimeError:
        raise
    except httpx.RequestError as exc:
        raise RuntimeError(
            f"Network error listing installation repos: {exc}"
        ) from exc

    logger.info(
        "github_app list_installation_repos  installation_id=%d  count=%d",
        installation_id,
        len(repos),
    )
    return repos
